// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GaussianBlur (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        fifo1_dout,
        fifo1_empty_n,
        fifo1_read,
        fifo2_din,
        fifo2_full_n,
        fifo2_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state8 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] fifo1_dout;
input   fifo1_empty_n;
output   fifo1_read;
output  [7:0] fifo2_din;
input   fifo2_full_n;
output   fifo2_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg fifo1_read;
reg fifo2_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    fifo1_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_66_i_reg_1284;
reg    fifo2_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] tmp_66_i_reg_1284_pp0_iter3_reg;
reg   [9:0] xi_i_reg_234;
wire   [0:0] tmp_i_fu_245_p2;
wire    ap_CS_fsm_state2;
wire   [9:0] yi_fu_251_p2;
reg   [9:0] yi_reg_1279;
wire   [0:0] tmp_66_i_fu_257_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
reg    ap_block_state7_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_66_i_reg_1284_pp0_iter1_reg;
reg   [0:0] tmp_66_i_reg_1284_pp0_iter2_reg;
wire   [9:0] xi_fu_263_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [8:0] line_buf_addr_reg_1293;
reg   [7:0] window_buf_0_3_1_reg_1299;
reg   [7:0] window_buf_1_1_6_reg_1304;
reg   [7:0] window_buf_1_2_1_reg_1310;
reg   [7:0] window_buf_2_1_6_reg_1316;
reg   [7:0] window_buf_2_2_1_reg_1323;
reg   [7:0] window_buf_2_3_1_reg_1329;
reg   [7:0] window_buf_3_2_1_reg_1335;
reg   [7:0] window_buf_0_4_reg_1341;
wire   [12:0] pix_gauss_2_0_2_i_fu_447_p2;
reg   [12:0] pix_gauss_2_0_2_i_reg_1346;
wire   [12:0] tmp9_fu_625_p2;
reg   [12:0] tmp9_reg_1351;
wire   [12:0] tmp12_fu_631_p2;
reg   [12:0] tmp12_reg_1356;
wire   [12:0] tmp13_fu_647_p2;
reg   [12:0] tmp13_reg_1361;
wire   [10:0] tmp16_fu_653_p2;
reg   [10:0] tmp16_reg_1366;
wire   [10:0] tmp17_fu_669_p2;
reg   [10:0] tmp17_reg_1371;
wire   [14:0] pix_gauss_2_1_1_i_fu_837_p2;
reg   [14:0] pix_gauss_2_1_1_i_reg_1376;
wire   [13:0] tmp_110_1_2_i_fu_865_p2;
reg   [13:0] tmp_110_1_2_i_reg_1381;
wire   [14:0] tmp5_fu_1033_p2;
reg   [14:0] tmp5_reg_1386;
wire   [15:0] tmp6_fu_1058_p2;
reg   [15:0] tmp6_reg_1391;
wire   [14:0] tmp10_fu_1096_p2;
reg   [14:0] tmp10_reg_1396;
reg   [7:0] tmp_71_i_reg_1401;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter1_state4;
reg    ap_enable_reg_pp0_iter3;
wire   [8:0] line_buf_address0;
reg    line_buf_ce0;
wire   [39:0] line_buf_q0;
reg    line_buf_ce1;
reg    line_buf_we1;
wire   [39:0] line_buf_d1;
reg   [9:0] yi_i_reg_223;
reg    ap_block_state1;
wire    ap_CS_fsm_state8;
wire   [63:0] tmp_67_i_fu_269_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] window_buf_0_1_fu_110;
reg   [7:0] window_buf_0_1_5_fu_114;
reg   [7:0] window_buf_0_2_fu_118;
reg   [7:0] window_buf_0_3_fu_122;
reg   [7:0] window_buf_1_1_fu_126;
reg   [7:0] window_buf_1_1_5_fu_130;
reg   [7:0] window_buf_1_2_fu_134;
reg   [7:0] window_buf_1_3_fu_138;
wire   [7:0] window_buf_1_4_fu_338_p4;
reg   [7:0] window_buf_2_1_fu_142;
reg   [7:0] window_buf_2_1_5_fu_146;
reg   [7:0] window_buf_2_2_fu_150;
reg   [7:0] window_buf_2_3_fu_154;
wire   [7:0] window_buf_2_4_fu_348_p4;
reg   [7:0] window_buf_3_1_fu_158;
reg   [7:0] window_buf_3_1_1_fu_162;
reg   [7:0] window_buf_3_2_fu_166;
reg   [7:0] window_buf_3_3_fu_170;
wire   [7:0] window_buf_3_4_fu_358_p4;
reg   [7:0] window_buf_4_1_fu_174;
reg   [7:0] window_buf_4_1_1_fu_178;
reg   [7:0] window_buf_4_2_fu_182;
reg   [7:0] window_buf_4_3_fu_186;
wire   [31:0] tmp_35_i_fu_368_p4;
wire   [9:0] tmp_110_0_1_i_fu_391_p3;
wire   [10:0] tmp_109_0_cast_i_fu_387_p1;
wire   [10:0] tmp_110_0_1_cast_i_fu_399_p1;
wire   [10:0] pix_gauss_2_0_1_i_fu_403_p2;
wire   [10:0] p_shl2_i_fu_413_p3;
wire   [8:0] p_shl3_i_fu_425_p3;
wire   [11:0] p_shl2_cast_i_fu_421_p1;
wire   [11:0] p_shl3_cast_i_fu_433_p1;
wire   [11:0] tmp_110_0_2_i_fu_437_p2;
wire   [12:0] pix_gauss_2_0_1_cast_fu_409_p1;
wire  signed [12:0] tmp_110_0_2_cast_i_fu_443_p1;
wire   [11:0] tmp_110_1_3_i_fu_453_p3;
wire   [9:0] tmp_110_1_4_i_fu_465_p3;
wire   [10:0] p_shl13_i_fu_477_p3;
wire   [8:0] p_shl14_i_fu_489_p3;
wire   [11:0] p_shl13_cast_i_fu_485_p1;
wire   [11:0] p_shl14_cast_i_fu_497_p1;
wire   [11:0] tmp_110_2_4_i_fu_501_p2;
wire   [9:0] tmp_110_3_i_fu_511_p3;
wire   [11:0] tmp_110_3_1_i_fu_523_p3;
wire   [11:0] tmp_110_3_3_i_fu_535_p3;
wire   [9:0] tmp_110_3_4_i_fu_547_p3;
wire   [9:0] tmp_110_4_1_i_fu_563_p3;
wire   [10:0] p_shl_i_fu_575_p3;
wire   [8:0] p_shl10_i_fu_587_p3;
wire   [11:0] p_shl_cast_i_fu_583_p1;
wire   [11:0] p_shl10_cast_i_fu_595_p1;
wire   [11:0] tmp_110_4_2_i_fu_599_p2;
wire   [9:0] tmp_110_4_3_i_fu_609_p3;
wire  signed [12:0] tmp_110_4_2_cast_i_c_fu_605_p1;
wire  signed [12:0] tmp_110_2_4_cast_i_c_fu_507_p1;
wire   [12:0] tmp_110_3_1_cast_i_c_fu_531_p1;
wire   [12:0] tmp_110_1_3_cast_i_c_fu_461_p1;
wire   [10:0] tmp_110_3_cast_i_cas_fu_519_p1;
wire   [10:0] tmp_110_1_4_cast_i_c_fu_473_p1;
wire   [10:0] tmp14_fu_637_p2;
wire   [12:0] tmp_110_3_3_cast_i_c_fu_543_p1;
wire   [12:0] tmp14_cast_fu_643_p1;
wire   [10:0] tmp_110_4_1_cast_i_c_fu_571_p1;
wire   [10:0] tmp_110_3_4_cast_i_c_fu_555_p1;
wire   [8:0] tmp_109_4_4_cast_i_c_fu_621_p1;
wire   [8:0] tmp_109_4_cast_i_cas_fu_559_p1;
wire   [8:0] tmp18_fu_659_p2;
wire   [10:0] tmp_110_4_3_cast_i_c_fu_617_p1;
wire   [10:0] tmp18_cast_fu_665_p1;
wire   [9:0] tmp_110_0_3_i_fu_774_p3;
wire   [9:0] tmp_110_1_i_fu_788_p3;
wire   [13:0] tmp_110_0_3_cast_i_fu_781_p1;
wire  signed [13:0] pix_gauss_2_0_2_cast_fu_771_p1;
wire   [10:0] tmp_109_0_4_cast_i_c_fu_785_p1;
wire   [10:0] tmp_110_1_cast_i_cas_fu_796_p1;
wire   [10:0] tmp1_fu_806_p2;
wire   [13:0] tmp_fu_800_p2;
wire   [13:0] tmp1_cast_fu_812_p1;
wire   [13:0] pix_gauss_2_1_i_fu_816_p2;
wire   [11:0] tmp_110_1_1_i_fu_826_p3;
wire   [14:0] tmp_110_1_1_cast_i_fu_833_p1;
wire  signed [14:0] pix_gauss_2_1_cast_i_fu_822_p1;
wire   [12:0] p_shl4_i_fu_843_p3;
wire   [10:0] p_shl5_i_fu_854_p3;
wire   [13:0] p_shl4_cast_i_fu_850_p1;
wire   [13:0] p_shl5_cast_i_fu_861_p1;
wire   [10:0] p_shl6_i_fu_871_p3;
wire   [8:0] p_shl7_i_fu_883_p3;
wire   [11:0] p_shl6_cast_i_fu_879_p1;
wire   [11:0] p_shl7_cast_i_fu_891_p1;
wire   [11:0] tmp_110_2_i_fu_895_p2;
wire   [12:0] p_shl8_i_fu_905_p3;
wire   [10:0] p_shl9_i_fu_916_p3;
wire   [13:0] p_shl8_cast_i_fu_912_p1;
wire   [13:0] p_shl9_cast_i_fu_923_p1;
wire   [13:0] tmp_110_2_1_i_fu_927_p2;
wire   [12:0] p_shl17_i_fu_937_p3;
wire   [9:0] p_shl18_i_fu_948_p3;
wire   [13:0] p_shl18_cast_i_fu_955_p1;
wire   [13:0] p_shl17_cast_i_fu_944_p1;
wire   [13:0] tmp_110_2_2_i_fu_959_p2;
wire   [12:0] p_shl15_i_fu_969_p3;
wire   [10:0] p_shl16_i_fu_980_p3;
wire   [13:0] p_shl15_cast_i_fu_976_p1;
wire   [13:0] p_shl16_cast_i_fu_987_p1;
wire   [13:0] tmp_110_2_3_i_fu_991_p2;
wire   [12:0] p_shl11_i_fu_1001_p3;
wire   [10:0] p_shl12_i_fu_1012_p3;
wire   [13:0] p_shl11_cast_i_fu_1008_p1;
wire   [13:0] p_shl12_cast_i_fu_1019_p1;
wire   [13:0] tmp_110_3_2_i_fu_1023_p2;
wire  signed [14:0] tmp_110_2_3_cast_i_c_fu_997_p1;
wire  signed [14:0] tmp_110_2_1_cast_i_c_fu_933_p1;
wire   [15:0] tmp_110_2_2_cast_i_fu_965_p1;
wire  signed [15:0] tmp_110_3_2_cast_i_fu_1029_p1;
wire  signed [13:0] tmp_110_2_cast_i_cas_fu_901_p1;
wire  signed [13:0] tmp9_cast_fu_1045_p1;
wire   [13:0] tmp8_fu_1048_p2;
wire   [15:0] tmp7_fu_1039_p2;
wire  signed [15:0] tmp8_cast_fu_1054_p1;
wire   [13:0] tmp12_cast_fu_1064_p1;
wire   [13:0] tmp13_cast_fu_1067_p1;
wire   [13:0] tmp11_fu_1070_p2;
wire   [11:0] tmp16_cast_fu_1080_p1;
wire   [11:0] tmp17_cast_fu_1083_p1;
wire   [11:0] tmp15_fu_1086_p2;
wire   [14:0] tmp11_cast_fu_1076_p1;
wire   [14:0] tmp15_cast_fu_1092_p1;
wire  signed [15:0] tmp_110_1_2_cast_i_fu_1113_p1;
wire  signed [15:0] pix_gauss_2_1_1_cast_fu_1110_p1;
wire   [15:0] tmp4_fu_1116_p2;
wire  signed [15:0] tmp5_cast_fu_1122_p1;
wire   [15:0] tmp3_fu_1125_p2;
wire   [15:0] tmp2_fu_1131_p2;
wire   [15:0] tmp10_cast_fu_1136_p1;
wire   [15:0] pix_gauss_2_4_4_i_fu_1139_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

GaussianBlur_lineeOg #(
    .DataWidth( 40 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
line_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buf_address0),
    .ce0(line_buf_ce0),
    .q0(line_buf_q0),
    .address1(line_buf_addr_reg_1293),
    .ce1(line_buf_ce1),
    .we1(line_buf_we1),
    .d1(line_buf_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((tmp_i_fu_245_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((tmp_66_i_fu_257_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((tmp_i_fu_245_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state4)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((tmp_i_fu_245_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_fu_245_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        xi_i_reg_234 <= 10'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_66_i_fu_257_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        xi_i_reg_234 <= xi_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        yi_i_reg_223 <= yi_reg_1279;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        yi_i_reg_223 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_66_i_fu_257_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_addr_reg_1293 <= tmp_67_i_fu_269_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_66_i_reg_1284 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_gauss_2_0_2_i_reg_1346 <= pix_gauss_2_0_2_i_fu_447_p2;
        tmp12_reg_1356[12 : 4] <= tmp12_fu_631_p2[12 : 4];
        tmp13_reg_1361[12 : 2] <= tmp13_fu_647_p2[12 : 2];
        tmp16_reg_1366[10 : 2] <= tmp16_fu_653_p2[10 : 2];
        tmp17_reg_1371 <= tmp17_fu_669_p2;
        tmp9_reg_1351[12 : 1] <= tmp9_fu_625_p2[12 : 1];
        window_buf_0_4_reg_1341 <= {{line_buf_q0[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_66_i_reg_1284_pp0_iter1_reg == 1'd0))) begin
        pix_gauss_2_1_1_i_reg_1376 <= pix_gauss_2_1_1_i_fu_837_p2;
        tmp10_reg_1396 <= tmp10_fu_1096_p2;
        tmp5_reg_1386[14 : 3] <= tmp5_fu_1033_p2[14 : 3];
        tmp6_reg_1391[15 : 1] <= tmp6_fu_1058_p2[15 : 1];
        tmp_110_1_2_i_reg_1381[13 : 3] <= tmp_110_1_2_i_fu_865_p2[13 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_66_i_reg_1284 <= tmp_66_i_fu_257_p2;
        tmp_66_i_reg_1284_pp0_iter1_reg <= tmp_66_i_reg_1284;
        window_buf_0_3_1_reg_1299 <= window_buf_0_3_fu_122;
        window_buf_1_1_6_reg_1304 <= window_buf_1_1_5_fu_130;
        window_buf_1_2_1_reg_1310 <= window_buf_1_2_fu_134;
        window_buf_2_1_6_reg_1316 <= window_buf_2_1_5_fu_146;
        window_buf_2_2_1_reg_1323 <= window_buf_2_2_fu_150;
        window_buf_2_3_1_reg_1329 <= window_buf_2_3_fu_154;
        window_buf_3_2_1_reg_1335 <= window_buf_3_2_fu_166;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        tmp_66_i_reg_1284_pp0_iter2_reg <= tmp_66_i_reg_1284_pp0_iter1_reg;
        tmp_66_i_reg_1284_pp0_iter3_reg <= tmp_66_i_reg_1284_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_66_i_reg_1284_pp0_iter2_reg == 1'd0))) begin
        tmp_71_i_reg_1401 <= {{pix_gauss_2_4_4_i_fu_1139_p2[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_66_i_reg_1284 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        window_buf_0_1_5_fu_114 <= window_buf_0_2_fu_118;
        window_buf_0_1_fu_110 <= window_buf_0_1_5_fu_114;
        window_buf_0_2_fu_118 <= window_buf_0_3_fu_122;
        window_buf_0_3_fu_122 <= {{line_buf_q0[15:8]}};
        window_buf_1_1_5_fu_130 <= window_buf_1_2_fu_134;
        window_buf_1_2_fu_134 <= window_buf_1_3_fu_138;
        window_buf_1_3_fu_138 <= {{line_buf_q0[23:16]}};
        window_buf_2_1_5_fu_146 <= window_buf_2_2_fu_150;
        window_buf_2_2_fu_150 <= window_buf_2_3_fu_154;
        window_buf_2_3_fu_154 <= {{line_buf_q0[31:24]}};
        window_buf_3_1_1_fu_162 <= window_buf_3_2_fu_166;
        window_buf_3_1_fu_158 <= window_buf_3_1_1_fu_162;
        window_buf_3_2_fu_166 <= window_buf_3_3_fu_170;
        window_buf_3_3_fu_170 <= {{line_buf_q0[39:32]}};
        window_buf_4_1_1_fu_178 <= window_buf_4_2_fu_182;
        window_buf_4_1_fu_174 <= window_buf_4_1_1_fu_178;
        window_buf_4_2_fu_182 <= window_buf_4_3_fu_186;
        window_buf_4_3_fu_186 <= fifo1_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_66_i_reg_1284_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        window_buf_1_1_fu_126 <= window_buf_1_1_6_reg_1304;
        window_buf_2_1_fu_142 <= window_buf_2_1_6_reg_1316;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        yi_reg_1279 <= yi_fu_251_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state4 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_fu_245_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_66_i_reg_1284 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo1_blk_n = fifo1_empty_n;
    end else begin
        fifo1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_66_i_reg_1284 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo1_read = 1'b1;
    end else begin
        fifo1_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_66_i_reg_1284_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        fifo2_blk_n = fifo2_full_n;
    end else begin
        fifo2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_66_i_reg_1284_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        fifo2_write = 1'b1;
    end else begin
        fifo2_write = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_fu_245_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        line_buf_ce0 = 1'b1;
    end else begin
        line_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_ce1 = 1'b1;
    end else begin
        line_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_66_i_reg_1284 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_we1 = 1'b1;
    end else begin
        line_buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_i_fu_245_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0)) & ~((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((tmp_66_i_reg_1284_pp0_iter3_reg == 1'd0) & (fifo2_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((tmp_66_i_reg_1284 == 1'd0) & (fifo1_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((tmp_66_i_reg_1284_pp0_iter3_reg == 1'd0) & (fifo2_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((tmp_66_i_reg_1284 == 1'd0) & (fifo1_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((tmp_66_i_reg_1284_pp0_iter3_reg == 1'd0) & (fifo2_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((tmp_66_i_reg_1284 == 1'd0) & (fifo1_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = ((tmp_66_i_reg_1284 == 1'd0) & (fifo1_empty_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter4 = ((tmp_66_i_reg_1284_pp0_iter3_reg == 1'd0) & (fifo2_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign fifo2_din = tmp_71_i_reg_1401;

assign line_buf_address0 = tmp_67_i_fu_269_p1;

assign line_buf_d1 = {{fifo1_dout}, {tmp_35_i_fu_368_p4}};

assign p_shl10_cast_i_fu_595_p1 = p_shl10_i_fu_587_p3;

assign p_shl10_i_fu_587_p3 = {{window_buf_4_2_fu_182}, {1'd0}};

assign p_shl11_cast_i_fu_1008_p1 = p_shl11_i_fu_1001_p3;

assign p_shl11_i_fu_1001_p3 = {{window_buf_3_2_1_reg_1335}, {5'd0}};

assign p_shl12_cast_i_fu_1019_p1 = p_shl12_i_fu_1012_p3;

assign p_shl12_i_fu_1012_p3 = {{window_buf_3_2_1_reg_1335}, {3'd0}};

assign p_shl13_cast_i_fu_485_p1 = p_shl13_i_fu_477_p3;

assign p_shl13_i_fu_477_p3 = {{window_buf_2_4_fu_348_p4}, {3'd0}};

assign p_shl14_cast_i_fu_497_p1 = p_shl14_i_fu_489_p3;

assign p_shl14_i_fu_489_p3 = {{window_buf_2_4_fu_348_p4}, {1'd0}};

assign p_shl15_cast_i_fu_976_p1 = p_shl15_i_fu_969_p3;

assign p_shl15_i_fu_969_p3 = {{window_buf_2_3_1_reg_1329}, {5'd0}};

assign p_shl16_cast_i_fu_987_p1 = p_shl16_i_fu_980_p3;

assign p_shl16_i_fu_980_p3 = {{window_buf_2_3_1_reg_1329}, {3'd0}};

assign p_shl17_cast_i_fu_944_p1 = p_shl17_i_fu_937_p3;

assign p_shl17_i_fu_937_p3 = {{window_buf_2_2_1_reg_1323}, {5'd0}};

assign p_shl18_cast_i_fu_955_p1 = p_shl18_i_fu_948_p3;

assign p_shl18_i_fu_948_p3 = {{window_buf_2_2_1_reg_1323}, {2'd0}};

assign p_shl2_cast_i_fu_421_p1 = p_shl2_i_fu_413_p3;

assign p_shl2_i_fu_413_p3 = {{window_buf_0_2_fu_118}, {3'd0}};

assign p_shl3_cast_i_fu_433_p1 = p_shl3_i_fu_425_p3;

assign p_shl3_i_fu_425_p3 = {{window_buf_0_2_fu_118}, {1'd0}};

assign p_shl4_cast_i_fu_850_p1 = p_shl4_i_fu_843_p3;

assign p_shl4_i_fu_843_p3 = {{window_buf_1_2_1_reg_1310}, {5'd0}};

assign p_shl5_cast_i_fu_861_p1 = p_shl5_i_fu_854_p3;

assign p_shl5_i_fu_854_p3 = {{window_buf_1_2_1_reg_1310}, {3'd0}};

assign p_shl6_cast_i_fu_879_p1 = p_shl6_i_fu_871_p3;

assign p_shl6_i_fu_871_p3 = {{window_buf_2_1_fu_142}, {3'd0}};

assign p_shl7_cast_i_fu_891_p1 = p_shl7_i_fu_883_p3;

assign p_shl7_i_fu_883_p3 = {{window_buf_2_1_fu_142}, {1'd0}};

assign p_shl8_cast_i_fu_912_p1 = p_shl8_i_fu_905_p3;

assign p_shl8_i_fu_905_p3 = {{window_buf_2_1_6_reg_1316}, {5'd0}};

assign p_shl9_cast_i_fu_923_p1 = p_shl9_i_fu_916_p3;

assign p_shl9_i_fu_916_p3 = {{window_buf_2_1_6_reg_1316}, {3'd0}};

assign p_shl_cast_i_fu_583_p1 = p_shl_i_fu_575_p3;

assign p_shl_i_fu_575_p3 = {{window_buf_4_2_fu_182}, {3'd0}};

assign pix_gauss_2_0_1_cast_fu_409_p1 = pix_gauss_2_0_1_i_fu_403_p2;

assign pix_gauss_2_0_1_i_fu_403_p2 = (tmp_109_0_cast_i_fu_387_p1 + tmp_110_0_1_cast_i_fu_399_p1);

assign pix_gauss_2_0_2_cast_fu_771_p1 = $signed(pix_gauss_2_0_2_i_reg_1346);

assign pix_gauss_2_0_2_i_fu_447_p2 = ($signed(pix_gauss_2_0_1_cast_fu_409_p1) + $signed(tmp_110_0_2_cast_i_fu_443_p1));

assign pix_gauss_2_1_1_cast_fu_1110_p1 = $signed(pix_gauss_2_1_1_i_reg_1376);

assign pix_gauss_2_1_1_i_fu_837_p2 = ($signed(tmp_110_1_1_cast_i_fu_833_p1) + $signed(pix_gauss_2_1_cast_i_fu_822_p1));

assign pix_gauss_2_1_cast_i_fu_822_p1 = $signed(pix_gauss_2_1_i_fu_816_p2);

assign pix_gauss_2_1_i_fu_816_p2 = (tmp_fu_800_p2 + tmp1_cast_fu_812_p1);

assign pix_gauss_2_4_4_i_fu_1139_p2 = (tmp2_fu_1131_p2 + tmp10_cast_fu_1136_p1);

assign start_out = real_start;

assign tmp10_cast_fu_1136_p1 = tmp10_reg_1396;

assign tmp10_fu_1096_p2 = (tmp11_cast_fu_1076_p1 + tmp15_cast_fu_1092_p1);

assign tmp11_cast_fu_1076_p1 = tmp11_fu_1070_p2;

assign tmp11_fu_1070_p2 = (tmp12_cast_fu_1064_p1 + tmp13_cast_fu_1067_p1);

assign tmp12_cast_fu_1064_p1 = tmp12_reg_1356;

assign tmp12_fu_631_p2 = (tmp_110_3_1_cast_i_c_fu_531_p1 + tmp_110_1_3_cast_i_c_fu_461_p1);

assign tmp13_cast_fu_1067_p1 = tmp13_reg_1361;

assign tmp13_fu_647_p2 = (tmp_110_3_3_cast_i_c_fu_543_p1 + tmp14_cast_fu_643_p1);

assign tmp14_cast_fu_643_p1 = tmp14_fu_637_p2;

assign tmp14_fu_637_p2 = (tmp_110_3_cast_i_cas_fu_519_p1 + tmp_110_1_4_cast_i_c_fu_473_p1);

assign tmp15_cast_fu_1092_p1 = tmp15_fu_1086_p2;

assign tmp15_fu_1086_p2 = (tmp16_cast_fu_1080_p1 + tmp17_cast_fu_1083_p1);

assign tmp16_cast_fu_1080_p1 = tmp16_reg_1366;

assign tmp16_fu_653_p2 = (tmp_110_4_1_cast_i_c_fu_571_p1 + tmp_110_3_4_cast_i_c_fu_555_p1);

assign tmp17_cast_fu_1083_p1 = tmp17_reg_1371;

assign tmp17_fu_669_p2 = (tmp_110_4_3_cast_i_c_fu_617_p1 + tmp18_cast_fu_665_p1);

assign tmp18_cast_fu_665_p1 = tmp18_fu_659_p2;

assign tmp18_fu_659_p2 = (tmp_109_4_4_cast_i_c_fu_621_p1 + tmp_109_4_cast_i_cas_fu_559_p1);

assign tmp1_cast_fu_812_p1 = tmp1_fu_806_p2;

assign tmp1_fu_806_p2 = (tmp_109_0_4_cast_i_c_fu_785_p1 + tmp_110_1_cast_i_cas_fu_796_p1);

assign tmp2_fu_1131_p2 = (tmp3_fu_1125_p2 + tmp6_reg_1391);

assign tmp3_fu_1125_p2 = ($signed(tmp4_fu_1116_p2) + $signed(tmp5_cast_fu_1122_p1));

assign tmp4_fu_1116_p2 = ($signed(tmp_110_1_2_cast_i_fu_1113_p1) + $signed(pix_gauss_2_1_1_cast_fu_1110_p1));

assign tmp5_cast_fu_1122_p1 = $signed(tmp5_reg_1386);

assign tmp5_fu_1033_p2 = ($signed(tmp_110_2_3_cast_i_c_fu_997_p1) + $signed(tmp_110_2_1_cast_i_c_fu_933_p1));

assign tmp6_fu_1058_p2 = ($signed(tmp7_fu_1039_p2) + $signed(tmp8_cast_fu_1054_p1));

assign tmp7_fu_1039_p2 = ($signed(tmp_110_2_2_cast_i_fu_965_p1) + $signed(tmp_110_3_2_cast_i_fu_1029_p1));

assign tmp8_cast_fu_1054_p1 = $signed(tmp8_fu_1048_p2);

assign tmp8_fu_1048_p2 = ($signed(tmp_110_2_cast_i_cas_fu_901_p1) + $signed(tmp9_cast_fu_1045_p1));

assign tmp9_cast_fu_1045_p1 = $signed(tmp9_reg_1351);

assign tmp9_fu_625_p2 = ($signed(tmp_110_4_2_cast_i_c_fu_605_p1) + $signed(tmp_110_2_4_cast_i_c_fu_507_p1));

assign tmp_109_0_4_cast_i_c_fu_785_p1 = window_buf_0_4_reg_1341;

assign tmp_109_0_cast_i_fu_387_p1 = window_buf_0_1_fu_110;

assign tmp_109_4_4_cast_i_c_fu_621_p1 = fifo1_dout;

assign tmp_109_4_cast_i_cas_fu_559_p1 = window_buf_4_1_fu_174;

assign tmp_110_0_1_cast_i_fu_399_p1 = tmp_110_0_1_i_fu_391_p3;

assign tmp_110_0_1_i_fu_391_p3 = {{window_buf_0_1_5_fu_114}, {2'd0}};

assign tmp_110_0_2_cast_i_fu_443_p1 = $signed(tmp_110_0_2_i_fu_437_p2);

assign tmp_110_0_2_i_fu_437_p2 = (p_shl2_cast_i_fu_421_p1 - p_shl3_cast_i_fu_433_p1);

assign tmp_110_0_3_cast_i_fu_781_p1 = tmp_110_0_3_i_fu_774_p3;

assign tmp_110_0_3_i_fu_774_p3 = {{window_buf_0_3_1_reg_1299}, {2'd0}};

assign tmp_110_1_1_cast_i_fu_833_p1 = tmp_110_1_1_i_fu_826_p3;

assign tmp_110_1_1_i_fu_826_p3 = {{window_buf_1_1_6_reg_1304}, {4'd0}};

assign tmp_110_1_2_cast_i_fu_1113_p1 = $signed(tmp_110_1_2_i_reg_1381);

assign tmp_110_1_2_i_fu_865_p2 = (p_shl4_cast_i_fu_850_p1 - p_shl5_cast_i_fu_861_p1);

assign tmp_110_1_3_cast_i_c_fu_461_p1 = tmp_110_1_3_i_fu_453_p3;

assign tmp_110_1_3_i_fu_453_p3 = {{window_buf_1_3_fu_138}, {4'd0}};

assign tmp_110_1_4_cast_i_c_fu_473_p1 = tmp_110_1_4_i_fu_465_p3;

assign tmp_110_1_4_i_fu_465_p3 = {{window_buf_1_4_fu_338_p4}, {2'd0}};

assign tmp_110_1_cast_i_cas_fu_796_p1 = tmp_110_1_i_fu_788_p3;

assign tmp_110_1_i_fu_788_p3 = {{window_buf_1_1_fu_126}, {2'd0}};

assign tmp_110_2_1_cast_i_c_fu_933_p1 = $signed(tmp_110_2_1_i_fu_927_p2);

assign tmp_110_2_1_i_fu_927_p2 = (p_shl8_cast_i_fu_912_p1 - p_shl9_cast_i_fu_923_p1);

assign tmp_110_2_2_cast_i_fu_965_p1 = tmp_110_2_2_i_fu_959_p2;

assign tmp_110_2_2_i_fu_959_p2 = (p_shl18_cast_i_fu_955_p1 + p_shl17_cast_i_fu_944_p1);

assign tmp_110_2_3_cast_i_c_fu_997_p1 = $signed(tmp_110_2_3_i_fu_991_p2);

assign tmp_110_2_3_i_fu_991_p2 = (p_shl15_cast_i_fu_976_p1 - p_shl16_cast_i_fu_987_p1);

assign tmp_110_2_4_cast_i_c_fu_507_p1 = $signed(tmp_110_2_4_i_fu_501_p2);

assign tmp_110_2_4_i_fu_501_p2 = (p_shl13_cast_i_fu_485_p1 - p_shl14_cast_i_fu_497_p1);

assign tmp_110_2_cast_i_cas_fu_901_p1 = $signed(tmp_110_2_i_fu_895_p2);

assign tmp_110_2_i_fu_895_p2 = (p_shl6_cast_i_fu_879_p1 - p_shl7_cast_i_fu_891_p1);

assign tmp_110_3_1_cast_i_c_fu_531_p1 = tmp_110_3_1_i_fu_523_p3;

assign tmp_110_3_1_i_fu_523_p3 = {{window_buf_3_1_1_fu_162}, {4'd0}};

assign tmp_110_3_2_cast_i_fu_1029_p1 = $signed(tmp_110_3_2_i_fu_1023_p2);

assign tmp_110_3_2_i_fu_1023_p2 = (p_shl11_cast_i_fu_1008_p1 - p_shl12_cast_i_fu_1019_p1);

assign tmp_110_3_3_cast_i_c_fu_543_p1 = tmp_110_3_3_i_fu_535_p3;

assign tmp_110_3_3_i_fu_535_p3 = {{window_buf_3_3_fu_170}, {4'd0}};

assign tmp_110_3_4_cast_i_c_fu_555_p1 = tmp_110_3_4_i_fu_547_p3;

assign tmp_110_3_4_i_fu_547_p3 = {{window_buf_3_4_fu_358_p4}, {2'd0}};

assign tmp_110_3_cast_i_cas_fu_519_p1 = tmp_110_3_i_fu_511_p3;

assign tmp_110_3_i_fu_511_p3 = {{window_buf_3_1_fu_158}, {2'd0}};

assign tmp_110_4_1_cast_i_c_fu_571_p1 = tmp_110_4_1_i_fu_563_p3;

assign tmp_110_4_1_i_fu_563_p3 = {{window_buf_4_1_1_fu_178}, {2'd0}};

assign tmp_110_4_2_cast_i_c_fu_605_p1 = $signed(tmp_110_4_2_i_fu_599_p2);

assign tmp_110_4_2_i_fu_599_p2 = (p_shl_cast_i_fu_583_p1 - p_shl10_cast_i_fu_595_p1);

assign tmp_110_4_3_cast_i_c_fu_617_p1 = tmp_110_4_3_i_fu_609_p3;

assign tmp_110_4_3_i_fu_609_p3 = {{window_buf_4_3_fu_186}, {2'd0}};

assign tmp_35_i_fu_368_p4 = {{line_buf_q0[39:8]}};

assign tmp_66_i_fu_257_p2 = ((xi_i_reg_234 == 10'd512) ? 1'b1 : 1'b0);

assign tmp_67_i_fu_269_p1 = xi_i_reg_234;

assign tmp_fu_800_p2 = ($signed(tmp_110_0_3_cast_i_fu_781_p1) + $signed(pix_gauss_2_0_2_cast_fu_771_p1));

assign tmp_i_fu_245_p2 = ((yi_i_reg_223 == 10'd512) ? 1'b1 : 1'b0);

assign window_buf_1_4_fu_338_p4 = {{line_buf_q0[23:16]}};

assign window_buf_2_4_fu_348_p4 = {{line_buf_q0[31:24]}};

assign window_buf_3_4_fu_358_p4 = {{line_buf_q0[39:32]}};

assign xi_fu_263_p2 = (xi_i_reg_234 + 10'd1);

assign yi_fu_251_p2 = (yi_i_reg_223 + 10'd1);

always @ (posedge ap_clk) begin
    tmp9_reg_1351[0] <= 1'b0;
    tmp12_reg_1356[3:0] <= 4'b0000;
    tmp13_reg_1361[1:0] <= 2'b00;
    tmp16_reg_1366[1:0] <= 2'b00;
    tmp_110_1_2_i_reg_1381[2:0] <= 3'b000;
    tmp5_reg_1386[2:0] <= 3'b000;
    tmp6_reg_1391[0] <= 1'b0;
end

endmodule //GaussianBlur
