// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Sobel_512u_512u_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        fifo2_dout,
        fifo2_empty_n,
        fifo2_read,
        fifo3_value_din,
        fifo3_value_full_n,
        fifo3_value_write,
        fifo3_grad_din,
        fifo3_grad_full_n,
        fifo3_grad_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state31 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] fifo2_dout;
input   fifo2_empty_n;
output   fifo2_read;
output  [7:0] fifo3_value_din;
input   fifo3_value_full_n;
output   fifo3_value_write;
output  [1:0] fifo3_grad_din;
input   fifo3_grad_full_n;
output   fifo3_grad_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg fifo2_read;
reg[7:0] fifo3_value_din;
reg fifo3_value_write;
reg fifo3_grad_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    fifo2_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_3_i_reg_959;
reg    fifo3_value_blk_n;
reg    ap_enable_reg_pp0_iter27;
reg   [0:0] or_cond3_i_reg_974;
reg   [0:0] or_cond3_i_reg_974_pp0_iter26_reg;
reg    fifo3_grad_blk_n;
reg   [9:0] xi_i_reg_242;
wire   [0:0] tmp_i_fu_272_p2;
wire    ap_CS_fsm_state2;
wire   [9:0] yi_fu_278_p2;
reg   [9:0] yi_reg_949;
wire   [0:0] tmp3_fu_306_p2;
reg   [0:0] tmp3_reg_954;
wire   [0:0] tmp_3_i_fu_312_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
wire    ap_block_state8_pp0_stage0_iter5;
wire    ap_block_state9_pp0_stage0_iter6;
wire    ap_block_state10_pp0_stage0_iter7;
wire    ap_block_state11_pp0_stage0_iter8;
wire    ap_block_state12_pp0_stage0_iter9;
wire    ap_block_state13_pp0_stage0_iter10;
wire    ap_block_state14_pp0_stage0_iter11;
wire    ap_block_state15_pp0_stage0_iter12;
wire    ap_block_state16_pp0_stage0_iter13;
wire    ap_block_state17_pp0_stage0_iter14;
wire    ap_block_state18_pp0_stage0_iter15;
wire    ap_block_state19_pp0_stage0_iter16;
wire    ap_block_state20_pp0_stage0_iter17;
wire    ap_block_state21_pp0_stage0_iter18;
wire    ap_block_state22_pp0_stage0_iter19;
wire    ap_block_state23_pp0_stage0_iter20;
wire    ap_block_state24_pp0_stage0_iter21;
wire    ap_block_state25_pp0_stage0_iter22;
wire    ap_block_state26_pp0_stage0_iter23;
wire    ap_block_state27_pp0_stage0_iter24;
wire    ap_block_state28_pp0_stage0_iter25;
wire    ap_block_state29_pp0_stage0_iter26;
reg    ap_block_state30_pp0_stage0_iter27;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_3_i_reg_959_pp0_iter1_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter2_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter3_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter4_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter5_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter6_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter7_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter8_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter9_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter10_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter11_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter12_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter13_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter14_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter15_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter16_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter17_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter18_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter19_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter20_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter21_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter22_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter23_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter24_reg;
reg   [0:0] tmp_3_i_reg_959_pp0_iter25_reg;
wire   [9:0] xi_fu_318_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [8:0] line_buf_addr_reg_968;
wire   [0:0] or_cond3_i_fu_357_p2;
reg   [0:0] or_cond3_i_reg_974_pp0_iter1_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter2_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter3_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter4_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter5_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter6_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter7_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter8_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter9_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter10_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter11_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter12_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter13_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter14_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter15_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter16_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter17_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter18_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter19_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter20_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter21_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter22_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter23_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter24_reg;
reg   [0:0] or_cond3_i_reg_974_pp0_iter25_reg;
reg   [7:0] window_buf_2_1_2_reg_978;
reg   [7:0] window_buf_1_2_reg_984;
reg   [7:0] window_buf_2_2_reg_989;
wire   [10:0] pix_h_sobel_2_1_1_i_fu_446_p2;
reg   [10:0] pix_h_sobel_2_1_1_i_reg_994;
wire   [9:0] pix_v_sobel_2_1_2_i_fu_474_p2;
reg   [9:0] pix_v_sobel_2_1_2_i_reg_999;
wire  signed [10:0] pix_h_sobel_2_2_2_i_fu_537_p2;
reg  signed [10:0] pix_h_sobel_2_2_2_i_reg_1004;
wire  signed [10:0] pix_v_sobel_2_2_2_i_fu_569_p2;
reg  signed [10:0] pix_v_sobel_2_2_2_i_reg_1010;
reg  signed [10:0] pix_v_sobel_2_2_2_i_reg_1010_pp0_iter3_reg;
wire   [0:0] tmp_16_i_fu_575_p2;
reg   [0:0] tmp_16_i_reg_1016;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter3_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter4_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter5_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter6_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter7_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter8_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter9_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter10_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter11_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter12_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter13_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter14_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter15_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter16_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter17_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter18_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter19_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter20_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter21_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter22_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter23_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter24_reg;
reg   [0:0] tmp_16_i_reg_1016_pp0_iter25_reg;
wire  signed [21:0] tmp_10_i_fu_896_p2;
reg  signed [21:0] tmp_10_i_reg_1020;
wire  signed [21:0] grp_fu_902_p3;
reg  signed [21:0] tmp_12_i_reg_1035;
reg    ap_enable_reg_pp0_iter4;
wire   [31:0] grp_fu_264_p1;
reg   [31:0] x_assign_reg_1045;
wire   [31:0] grp_fu_267_p2;
reg   [31:0] x_assign_2_reg_1050;
reg   [0:0] p_Result_s_reg_1055;
wire   [31:0] p_Val2_5_fu_736_p3;
reg   [31:0] p_Val2_5_reg_1060;
wire   [7:0] tmp_28_i_fu_775_p3;
reg   [7:0] tmp_28_i_reg_1066;
reg   [7:0] tmp_28_i_reg_1066_pp0_iter24_reg;
reg   [7:0] tmp_28_i_reg_1066_pp0_iter25_reg;
reg   [7:0] tmp_28_i_reg_1066_pp0_iter26_reg;
wire  signed [31:0] t_int_fu_783_p1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter1_state4;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
wire   [8:0] line_buf_address0;
reg    line_buf_ce0;
wire   [23:0] line_buf_q0;
reg    line_buf_ce1;
reg    line_buf_we1;
wire   [23:0] line_buf_d1;
reg   [9:0] yi_i_reg_231;
reg    ap_block_state1;
wire    ap_CS_fsm_state31;
wire   [31:0] ap_phi_reg_pp0_iter0_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter1_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter2_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter3_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter4_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter5_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter6_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter7_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter8_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter9_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter10_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter11_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter12_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter13_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter14_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter15_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter16_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter17_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter18_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter19_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter20_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter21_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter22_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter23_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter24_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter25_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter26_t_int1_i_reg_253;
reg   [31:0] ap_phi_reg_pp0_iter27_t_int1_i_reg_253;
wire   [63:0] tmp_4_i_fu_324_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] window_buf_0_1_fu_166;
reg   [7:0] window_buf_0_1_1_fu_170;
wire   [7:0] window_buf_0_2_fu_377_p4;
reg   [7:0] window_buf_1_1_fu_174;
reg   [7:0] window_buf_1_1_1_fu_178;
reg   [7:0] window_buf_2_1_fu_182;
reg   [7:0] window_buf_2_1_1_fu_186;
wire  signed [31:0] grp_fu_264_p0;
wire   [7:0] tmp_2_fu_284_p4;
wire   [0:0] icmp_fu_294_p2;
wire   [0:0] tmp_2_i_fu_300_p2;
wire   [7:0] tmp_10_fu_329_p4;
wire   [0:0] icmp8_fu_339_p2;
wire   [0:0] tmp_26_i_fu_345_p2;
wire   [0:0] tmp2_fu_351_p2;
wire   [15:0] tmp_8_i_fu_397_p4;
wire   [8:0] tmp_23_0_cast10_i_ca_fu_416_p1;
wire   [8:0] tmp_23_0_2_cast9_i_c_fu_420_p1;
wire   [8:0] pix_h_sobel_2_0_2_i_fu_424_p2;
wire   [8:0] tmp_24_1_i_fu_434_p3;
wire   [10:0] tmp_24_1_cast_i_fu_442_p1;
wire  signed [10:0] pix_h_sobel_2_0_2_ca_fu_430_p1;
wire   [8:0] tmp_30_0_1_i_fu_452_p3;
wire   [8:0] tmp_fu_464_p2;
wire   [9:0] tmp_cast_fu_470_p1;
wire   [9:0] tmp_30_0_1_cast_i_fu_460_p1;
wire   [8:0] p_shl1_i_fu_508_p3;
wire   [10:0] p_shl1_cast_i_fu_515_p1;
wire   [10:0] pix_h_sobel_2_1_2_i_fu_519_p2;
wire   [10:0] tmp_23_2_cast_i_fu_524_p1;
wire   [10:0] pix_h_sobel_2_2_1_i_fu_528_p2;
wire   [10:0] tmp_23_2_2_cast_i_fu_534_p1;
wire   [10:0] pix_v_sobel_2_1_2_ca_fu_543_p1;
wire   [8:0] p_shl_i_fu_552_p3;
wire   [10:0] pix_v_sobel_2_2_i_fu_546_p2;
wire   [10:0] p_shl_cast_i_fu_559_p1;
wire   [10:0] pix_v_sobel_2_2_1_i_fu_563_p2;
wire   [18:0] tmp_25_tr_i_fu_588_p3;
wire  signed [19:0] grp_fu_602_p0;
wire   [31:0] p_Val2_s_fu_615_p1;
wire   [22:0] tmp_V_1_fu_636_p1;
wire   [24:0] mantissa_V_fu_640_p4;
wire   [7:0] tmp_V_fu_626_p4;
wire   [8:0] tmp_i_i_i_i_cast_i_fu_654_p1;
wire   [8:0] sh_assign_fu_658_p2;
wire   [7:0] tmp_i_i_i_i_fu_672_p2;
wire   [0:0] isNeg_fu_664_p3;
wire  signed [8:0] tmp_i_i_i_cast_i_fu_678_p1;
wire  signed [8:0] ush_fu_682_p3;
wire  signed [31:0] sh_assign_2_i_i_i_ca_fu_690_p1;
wire  signed [24:0] sh_assign_2_i_i_i_ca_1_fu_694_p1;
wire   [78:0] mantissa_V_1_i_i_i_c_fu_650_p1;
wire   [78:0] tmp_i_i_i_i_96_fu_698_p1;
wire   [24:0] r_V_fu_702_p2;
wire   [0:0] tmp_8_fu_714_p3;
wire   [78:0] r_V_1_fu_708_p2;
wire   [31:0] tmp_4_fu_722_p1;
wire   [31:0] tmp_5_fu_726_p4;
wire   [31:0] result_V_1_fu_744_p2;
wire   [31:0] p_Val2_6_fu_749_p3;
wire   [23:0] tmp_9_fu_755_p4;
wire   [0:0] icmp5_fu_765_p2;
wire   [7:0] tmp_11_fu_771_p1;
wire   [19:0] grp_fu_602_p2;
wire   [0:0] tmp_19_i_fu_787_p2;
wire   [0:0] tmp_20_i_fu_793_p2;
wire   [0:0] tmp_23_i_fu_817_p2;
wire   [0:0] tmp_24_i_fu_823_p2;
wire   [0:0] or_cond9_i_fu_829_p2;
wire   [0:0] sel_tmp1_demorgan_fu_843_p2;
wire   [0:0] tmp_22_i_fu_811_p2;
wire   [0:0] sel_tmp1_fu_849_p2;
wire   [0:0] tmp1_fu_855_p2;
wire   [0:0] tmp_21_i_fu_805_p2;
wire   [0:0] sel_tmp2_fu_861_p2;
wire   [0:0] not_sel_tmp2_fu_867_p2;
wire   [0:0] or_cond_i_fu_799_p2;
wire   [0:0] tmp_1_fu_881_p2;
wire   [1:0] sel_tmp_cast_fu_873_p3;
wire   [1:0] grad_sobel_i_fu_835_p3;
wire  signed [10:0] tmp_10_i_fu_896_p0;
wire  signed [21:0] pix_h_sobel_2_2_2_ca_fu_585_p1;
wire  signed [10:0] tmp_10_i_fu_896_p1;
wire  signed [10:0] grp_fu_902_p0;
wire  signed [21:0] pix_v_sobel_2_2_2_ca_fu_608_p1;
wire  signed [10:0] grp_fu_902_p1;
reg    grp_fu_264_ce;
reg    grp_fu_267_ce;
reg    grp_fu_602_ce;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
end

Sobel_512u_512u_sfYi #(
    .DataWidth( 24 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
line_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buf_address0),
    .ce0(line_buf_ce0),
    .q0(line_buf_q0),
    .address1(line_buf_addr_reg_968),
    .ce1(line_buf_ce1),
    .we1(line_buf_we1),
    .d1(line_buf_d1)
);

canny_edge_detectg8j #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
canny_edge_detectg8j_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_264_p0),
    .ce(grp_fu_264_ce),
    .dout(grp_fu_264_p1)
);

canny_edge_detecthbi #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
canny_edge_detecthbi_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(x_assign_reg_1045),
    .ce(grp_fu_267_ce),
    .dout(grp_fu_267_p2)
);

canny_edge_detectibs #(
    .ID( 1 ),
    .NUM_STAGE( 24 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 20 ))
canny_edge_detectibs_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_602_p0),
    .din1(pix_h_sobel_2_2_2_i_reg_1004),
    .ce(grp_fu_602_ce),
    .dout(grp_fu_602_p2)
);

canny_edge_detectjbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 22 ))
canny_edge_detectjbC_U25(
    .din0(tmp_10_i_fu_896_p0),
    .din1(tmp_10_i_fu_896_p1),
    .dout(tmp_10_i_fu_896_p2)
);

canny_edge_detectkbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
canny_edge_detectkbM_U26(
    .din0(grp_fu_902_p0),
    .din1(grp_fu_902_p1),
    .din2(tmp_10_i_reg_1020),
    .dout(grp_fu_902_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((tmp_i_fu_272_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((tmp_3_i_fu_312_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((tmp_i_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state4)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end else if (((tmp_i_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter27 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((tmp_16_i_reg_1016_pp0_iter25_reg == 1'd0) & (tmp_3_i_reg_959_pp0_iter25_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter27_t_int1_i_reg_253 <= t_int_fu_783_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter27_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter26_t_int1_i_reg_253;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((tmp_16_i_fu_575_p2 == 1'd1) & (tmp_3_i_reg_959_pp0_iter1_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter3_t_int1_i_reg_253 <= 32'd2147483647;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter2_t_int1_i_reg_253;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_fu_312_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        xi_i_reg_242 <= xi_fu_318_p2;
    end else if (((tmp_i_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        xi_i_reg_242 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        yi_i_reg_231 <= yi_reg_949;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        yi_i_reg_231 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter9_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter10_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter11_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter13_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter12_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter14_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter13_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter15_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter14_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter16_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter15_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter17_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter16_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter18_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter17_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter19_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter18_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter0_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter20_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter19_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter21_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter20_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter22_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter21_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter23_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter22_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter24_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter23_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter25_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter24_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter26_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter25_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter1_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter3_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter4_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter5_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter6_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter7_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_t_int1_i_reg_253 <= ap_phi_reg_pp0_iter8_t_int1_i_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_fu_312_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_addr_reg_968 <= tmp_4_i_fu_324_p1;
        or_cond3_i_reg_974 <= or_cond3_i_fu_357_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        or_cond3_i_reg_974_pp0_iter10_reg <= or_cond3_i_reg_974_pp0_iter9_reg;
        or_cond3_i_reg_974_pp0_iter11_reg <= or_cond3_i_reg_974_pp0_iter10_reg;
        or_cond3_i_reg_974_pp0_iter12_reg <= or_cond3_i_reg_974_pp0_iter11_reg;
        or_cond3_i_reg_974_pp0_iter13_reg <= or_cond3_i_reg_974_pp0_iter12_reg;
        or_cond3_i_reg_974_pp0_iter14_reg <= or_cond3_i_reg_974_pp0_iter13_reg;
        or_cond3_i_reg_974_pp0_iter15_reg <= or_cond3_i_reg_974_pp0_iter14_reg;
        or_cond3_i_reg_974_pp0_iter16_reg <= or_cond3_i_reg_974_pp0_iter15_reg;
        or_cond3_i_reg_974_pp0_iter17_reg <= or_cond3_i_reg_974_pp0_iter16_reg;
        or_cond3_i_reg_974_pp0_iter18_reg <= or_cond3_i_reg_974_pp0_iter17_reg;
        or_cond3_i_reg_974_pp0_iter19_reg <= or_cond3_i_reg_974_pp0_iter18_reg;
        or_cond3_i_reg_974_pp0_iter20_reg <= or_cond3_i_reg_974_pp0_iter19_reg;
        or_cond3_i_reg_974_pp0_iter21_reg <= or_cond3_i_reg_974_pp0_iter20_reg;
        or_cond3_i_reg_974_pp0_iter22_reg <= or_cond3_i_reg_974_pp0_iter21_reg;
        or_cond3_i_reg_974_pp0_iter23_reg <= or_cond3_i_reg_974_pp0_iter22_reg;
        or_cond3_i_reg_974_pp0_iter24_reg <= or_cond3_i_reg_974_pp0_iter23_reg;
        or_cond3_i_reg_974_pp0_iter25_reg <= or_cond3_i_reg_974_pp0_iter24_reg;
        or_cond3_i_reg_974_pp0_iter26_reg <= or_cond3_i_reg_974_pp0_iter25_reg;
        or_cond3_i_reg_974_pp0_iter2_reg <= or_cond3_i_reg_974_pp0_iter1_reg;
        or_cond3_i_reg_974_pp0_iter3_reg <= or_cond3_i_reg_974_pp0_iter2_reg;
        or_cond3_i_reg_974_pp0_iter4_reg <= or_cond3_i_reg_974_pp0_iter3_reg;
        or_cond3_i_reg_974_pp0_iter5_reg <= or_cond3_i_reg_974_pp0_iter4_reg;
        or_cond3_i_reg_974_pp0_iter6_reg <= or_cond3_i_reg_974_pp0_iter5_reg;
        or_cond3_i_reg_974_pp0_iter7_reg <= or_cond3_i_reg_974_pp0_iter6_reg;
        or_cond3_i_reg_974_pp0_iter8_reg <= or_cond3_i_reg_974_pp0_iter7_reg;
        or_cond3_i_reg_974_pp0_iter9_reg <= or_cond3_i_reg_974_pp0_iter8_reg;
        pix_v_sobel_2_2_2_i_reg_1010_pp0_iter3_reg <= pix_v_sobel_2_2_2_i_reg_1010;
        tmp_16_i_reg_1016_pp0_iter10_reg <= tmp_16_i_reg_1016_pp0_iter9_reg;
        tmp_16_i_reg_1016_pp0_iter11_reg <= tmp_16_i_reg_1016_pp0_iter10_reg;
        tmp_16_i_reg_1016_pp0_iter12_reg <= tmp_16_i_reg_1016_pp0_iter11_reg;
        tmp_16_i_reg_1016_pp0_iter13_reg <= tmp_16_i_reg_1016_pp0_iter12_reg;
        tmp_16_i_reg_1016_pp0_iter14_reg <= tmp_16_i_reg_1016_pp0_iter13_reg;
        tmp_16_i_reg_1016_pp0_iter15_reg <= tmp_16_i_reg_1016_pp0_iter14_reg;
        tmp_16_i_reg_1016_pp0_iter16_reg <= tmp_16_i_reg_1016_pp0_iter15_reg;
        tmp_16_i_reg_1016_pp0_iter17_reg <= tmp_16_i_reg_1016_pp0_iter16_reg;
        tmp_16_i_reg_1016_pp0_iter18_reg <= tmp_16_i_reg_1016_pp0_iter17_reg;
        tmp_16_i_reg_1016_pp0_iter19_reg <= tmp_16_i_reg_1016_pp0_iter18_reg;
        tmp_16_i_reg_1016_pp0_iter20_reg <= tmp_16_i_reg_1016_pp0_iter19_reg;
        tmp_16_i_reg_1016_pp0_iter21_reg <= tmp_16_i_reg_1016_pp0_iter20_reg;
        tmp_16_i_reg_1016_pp0_iter22_reg <= tmp_16_i_reg_1016_pp0_iter21_reg;
        tmp_16_i_reg_1016_pp0_iter23_reg <= tmp_16_i_reg_1016_pp0_iter22_reg;
        tmp_16_i_reg_1016_pp0_iter24_reg <= tmp_16_i_reg_1016_pp0_iter23_reg;
        tmp_16_i_reg_1016_pp0_iter25_reg <= tmp_16_i_reg_1016_pp0_iter24_reg;
        tmp_16_i_reg_1016_pp0_iter3_reg <= tmp_16_i_reg_1016;
        tmp_16_i_reg_1016_pp0_iter4_reg <= tmp_16_i_reg_1016_pp0_iter3_reg;
        tmp_16_i_reg_1016_pp0_iter5_reg <= tmp_16_i_reg_1016_pp0_iter4_reg;
        tmp_16_i_reg_1016_pp0_iter6_reg <= tmp_16_i_reg_1016_pp0_iter5_reg;
        tmp_16_i_reg_1016_pp0_iter7_reg <= tmp_16_i_reg_1016_pp0_iter6_reg;
        tmp_16_i_reg_1016_pp0_iter8_reg <= tmp_16_i_reg_1016_pp0_iter7_reg;
        tmp_16_i_reg_1016_pp0_iter9_reg <= tmp_16_i_reg_1016_pp0_iter8_reg;
        tmp_28_i_reg_1066_pp0_iter24_reg <= tmp_28_i_reg_1066;
        tmp_28_i_reg_1066_pp0_iter25_reg <= tmp_28_i_reg_1066_pp0_iter24_reg;
        tmp_28_i_reg_1066_pp0_iter26_reg <= tmp_28_i_reg_1066_pp0_iter25_reg;
        tmp_3_i_reg_959_pp0_iter10_reg <= tmp_3_i_reg_959_pp0_iter9_reg;
        tmp_3_i_reg_959_pp0_iter11_reg <= tmp_3_i_reg_959_pp0_iter10_reg;
        tmp_3_i_reg_959_pp0_iter12_reg <= tmp_3_i_reg_959_pp0_iter11_reg;
        tmp_3_i_reg_959_pp0_iter13_reg <= tmp_3_i_reg_959_pp0_iter12_reg;
        tmp_3_i_reg_959_pp0_iter14_reg <= tmp_3_i_reg_959_pp0_iter13_reg;
        tmp_3_i_reg_959_pp0_iter15_reg <= tmp_3_i_reg_959_pp0_iter14_reg;
        tmp_3_i_reg_959_pp0_iter16_reg <= tmp_3_i_reg_959_pp0_iter15_reg;
        tmp_3_i_reg_959_pp0_iter17_reg <= tmp_3_i_reg_959_pp0_iter16_reg;
        tmp_3_i_reg_959_pp0_iter18_reg <= tmp_3_i_reg_959_pp0_iter17_reg;
        tmp_3_i_reg_959_pp0_iter19_reg <= tmp_3_i_reg_959_pp0_iter18_reg;
        tmp_3_i_reg_959_pp0_iter20_reg <= tmp_3_i_reg_959_pp0_iter19_reg;
        tmp_3_i_reg_959_pp0_iter21_reg <= tmp_3_i_reg_959_pp0_iter20_reg;
        tmp_3_i_reg_959_pp0_iter22_reg <= tmp_3_i_reg_959_pp0_iter21_reg;
        tmp_3_i_reg_959_pp0_iter23_reg <= tmp_3_i_reg_959_pp0_iter22_reg;
        tmp_3_i_reg_959_pp0_iter24_reg <= tmp_3_i_reg_959_pp0_iter23_reg;
        tmp_3_i_reg_959_pp0_iter25_reg <= tmp_3_i_reg_959_pp0_iter24_reg;
        tmp_3_i_reg_959_pp0_iter2_reg <= tmp_3_i_reg_959_pp0_iter1_reg;
        tmp_3_i_reg_959_pp0_iter3_reg <= tmp_3_i_reg_959_pp0_iter2_reg;
        tmp_3_i_reg_959_pp0_iter4_reg <= tmp_3_i_reg_959_pp0_iter3_reg;
        tmp_3_i_reg_959_pp0_iter5_reg <= tmp_3_i_reg_959_pp0_iter4_reg;
        tmp_3_i_reg_959_pp0_iter6_reg <= tmp_3_i_reg_959_pp0_iter5_reg;
        tmp_3_i_reg_959_pp0_iter7_reg <= tmp_3_i_reg_959_pp0_iter6_reg;
        tmp_3_i_reg_959_pp0_iter8_reg <= tmp_3_i_reg_959_pp0_iter7_reg;
        tmp_3_i_reg_959_pp0_iter9_reg <= tmp_3_i_reg_959_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_cond3_i_reg_974_pp0_iter1_reg <= or_cond3_i_reg_974;
        tmp_3_i_reg_959 <= tmp_3_i_fu_312_p2;
        tmp_3_i_reg_959_pp0_iter1_reg <= tmp_3_i_reg_959;
        window_buf_2_1_2_reg_978 <= window_buf_2_1_1_fu_186;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_reg_959_pp0_iter21_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Result_s_reg_1055 <= p_Val2_s_fu_615_p1[32'd31];
        p_Val2_5_reg_1060 <= p_Val2_5_fu_736_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_reg_959 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pix_h_sobel_2_1_1_i_reg_994 <= pix_h_sobel_2_1_1_i_fu_446_p2;
        pix_v_sobel_2_1_2_i_reg_999 <= pix_v_sobel_2_1_2_i_fu_474_p2;
        window_buf_1_2_reg_984 <= {{line_buf_q0[23:16]}};
        window_buf_2_2_reg_989 <= fifo2_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_reg_959_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pix_h_sobel_2_2_2_i_reg_1004 <= pix_h_sobel_2_2_2_i_fu_537_p2;
        pix_v_sobel_2_2_2_i_reg_1010 <= pix_v_sobel_2_2_2_i_fu_569_p2;
        tmp_16_i_reg_1016 <= tmp_16_i_fu_575_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp3_reg_954 <= tmp3_fu_306_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_reg_959_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_10_i_reg_1020 <= tmp_10_i_fu_896_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_reg_959_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_12_i_reg_1035 <= grp_fu_902_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond3_i_reg_974_pp0_iter22_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_28_i_reg_1066 <= tmp_28_i_fu_775_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_reg_959 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        window_buf_0_1_1_fu_170 <= {{line_buf_q0[15:8]}};
        window_buf_0_1_fu_166 <= window_buf_0_1_1_fu_170;
        window_buf_1_1_1_fu_178 <= {{line_buf_q0[23:16]}};
        window_buf_1_1_fu_174 <= window_buf_1_1_1_fu_178;
        window_buf_2_1_1_fu_186 <= fifo2_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_reg_959_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        window_buf_2_1_fu_182 <= window_buf_2_1_2_reg_978;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_reg_959_pp0_iter20_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_assign_2_reg_1050 <= grp_fu_267_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_reg_959_pp0_iter8_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_assign_reg_1045 <= grp_fu_264_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        yi_reg_949 <= yi_fu_278_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state4 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_fu_272_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_3_i_reg_959 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo2_blk_n = fifo2_empty_n;
    end else begin
        fifo2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_3_i_reg_959 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fifo2_read = 1'b1;
    end else begin
        fifo2_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter27 == 1'b1)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter27 == 1'b1)))) begin
        fifo3_grad_blk_n = fifo3_grad_full_n;
    end else begin
        fifo3_grad_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (ap_enable_reg_pp0_iter27 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (ap_enable_reg_pp0_iter27 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        fifo3_grad_write = 1'b1;
    end else begin
        fifo3_grad_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter27 == 1'b1)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter27 == 1'b1)))) begin
        fifo3_value_blk_n = fifo3_value_full_n;
    end else begin
        fifo3_value_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        if ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1)) begin
            fifo3_value_din = tmp_28_i_reg_1066_pp0_iter26_reg;
        end else if ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0)) begin
            fifo3_value_din = 8'd0;
        end else begin
            fifo3_value_din = 'bx;
        end
    end else begin
        fifo3_value_din = 'bx;
    end
end

always @ (*) begin
    if ((((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (ap_enable_reg_pp0_iter27 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (ap_enable_reg_pp0_iter27 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        fifo3_value_write = 1'b1;
    end else begin
        fifo3_value_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_264_ce = 1'b1;
    end else begin
        grp_fu_264_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_267_ce = 1'b1;
    end else begin
        grp_fu_267_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_602_ce = 1'b1;
    end else begin
        grp_fu_602_ce = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_fu_272_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_ce0 = 1'b1;
    end else begin
        line_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_ce1 = 1'b1;
    end else begin
        line_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_3_i_reg_959 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_we1 = 1'b1;
    end else begin
        line_buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_i_fu_272_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)) & ~((ap_enable_reg_pp0_iter26 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter27 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter26 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter27 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter27 == 1'b1) & (((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (fifo3_grad_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (fifo3_value_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (fifo3_grad_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (fifo3_value_full_n == 1'b0)))) | ((tmp_3_i_reg_959 == 1'd0) & (fifo2_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter27 == 1'b1) & (((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (fifo3_grad_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (fifo3_value_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (fifo3_grad_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (fifo3_value_full_n == 1'b0)))) | ((tmp_3_i_reg_959 == 1'd0) & (fifo2_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter27 == 1'b1) & (((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (fifo3_grad_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (fifo3_value_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (fifo3_grad_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (fifo3_value_full_n == 1'b0)))) | ((tmp_3_i_reg_959 == 1'd0) & (fifo2_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state30_pp0_stage0_iter27 = (((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (fifo3_grad_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd0) & (fifo3_value_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (fifo3_grad_full_n == 1'b0)) | ((or_cond3_i_reg_974_pp0_iter26_reg == 1'd1) & (fifo3_value_full_n == 1'b0)));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = ((tmp_3_i_reg_959 == 1'd0) & (fifo2_empty_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_t_int1_i_reg_253 = 'bx;

assign ap_ready = internal_ap_ready;

assign fifo3_grad_din = ((tmp_1_fu_881_p2[0:0] === 1'b1) ? sel_tmp_cast_fu_873_p3 : grad_sobel_i_fu_835_p3);

assign grad_sobel_i_fu_835_p3 = ((or_cond9_i_fu_829_p2[0:0] === 1'b1) ? 2'd1 : 2'd2);

assign grp_fu_264_p0 = tmp_12_i_reg_1035;

assign grp_fu_602_p0 = $signed(tmp_25_tr_i_fu_588_p3);

assign grp_fu_902_p0 = pix_v_sobel_2_2_2_ca_fu_608_p1;

assign grp_fu_902_p1 = pix_v_sobel_2_2_2_ca_fu_608_p1;

assign icmp5_fu_765_p2 = (($signed(tmp_9_fu_755_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp8_fu_339_p2 = ((tmp_10_fu_329_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_fu_294_p2 = ((tmp_2_fu_284_p4 != 8'd0) ? 1'b1 : 1'b0);

assign isNeg_fu_664_p3 = sh_assign_fu_658_p2[32'd8];

assign line_buf_address0 = tmp_4_i_fu_324_p1;

assign line_buf_d1 = {{fifo2_dout}, {tmp_8_i_fu_397_p4}};

assign mantissa_V_1_i_i_i_c_fu_650_p1 = mantissa_V_fu_640_p4;

assign mantissa_V_fu_640_p4 = {{{{1'd1}, {tmp_V_1_fu_636_p1}}}, {1'd0}};

assign not_sel_tmp2_fu_867_p2 = (sel_tmp2_fu_861_p2 ^ 1'd1);

assign or_cond3_i_fu_357_p2 = (tmp3_reg_954 & tmp2_fu_351_p2);

assign or_cond9_i_fu_829_p2 = (tmp_24_i_fu_823_p2 & tmp_23_i_fu_817_p2);

assign or_cond_i_fu_799_p2 = (tmp_20_i_fu_793_p2 & tmp_19_i_fu_787_p2);

assign p_Val2_5_fu_736_p3 = ((isNeg_fu_664_p3[0:0] === 1'b1) ? tmp_4_fu_722_p1 : tmp_5_fu_726_p4);

assign p_Val2_6_fu_749_p3 = ((p_Result_s_reg_1055[0:0] === 1'b1) ? result_V_1_fu_744_p2 : p_Val2_5_reg_1060);

assign p_Val2_s_fu_615_p1 = x_assign_2_reg_1050;

assign p_shl1_cast_i_fu_515_p1 = p_shl1_i_fu_508_p3;

assign p_shl1_i_fu_508_p3 = {{window_buf_1_2_reg_984}, {1'd0}};

assign p_shl_cast_i_fu_559_p1 = p_shl_i_fu_552_p3;

assign p_shl_i_fu_552_p3 = {{window_buf_2_1_2_reg_978}, {1'd0}};

assign pix_h_sobel_2_0_2_ca_fu_430_p1 = $signed(pix_h_sobel_2_0_2_i_fu_424_p2);

assign pix_h_sobel_2_0_2_i_fu_424_p2 = (tmp_23_0_cast10_i_ca_fu_416_p1 - tmp_23_0_2_cast9_i_c_fu_420_p1);

assign pix_h_sobel_2_1_1_i_fu_446_p2 = ($signed(tmp_24_1_cast_i_fu_442_p1) + $signed(pix_h_sobel_2_0_2_ca_fu_430_p1));

assign pix_h_sobel_2_1_2_i_fu_519_p2 = (pix_h_sobel_2_1_1_i_reg_994 - p_shl1_cast_i_fu_515_p1);

assign pix_h_sobel_2_2_1_i_fu_528_p2 = (pix_h_sobel_2_1_2_i_fu_519_p2 + tmp_23_2_cast_i_fu_524_p1);

assign pix_h_sobel_2_2_2_ca_fu_585_p1 = pix_h_sobel_2_2_2_i_reg_1004;

assign pix_h_sobel_2_2_2_i_fu_537_p2 = (pix_h_sobel_2_2_1_i_fu_528_p2 - tmp_23_2_2_cast_i_fu_534_p1);

assign pix_v_sobel_2_1_2_ca_fu_543_p1 = pix_v_sobel_2_1_2_i_reg_999;

assign pix_v_sobel_2_1_2_i_fu_474_p2 = (tmp_cast_fu_470_p1 + tmp_30_0_1_cast_i_fu_460_p1);

assign pix_v_sobel_2_2_1_i_fu_563_p2 = (pix_v_sobel_2_2_i_fu_546_p2 - p_shl_cast_i_fu_559_p1);

assign pix_v_sobel_2_2_2_ca_fu_608_p1 = pix_v_sobel_2_2_2_i_reg_1010_pp0_iter3_reg;

assign pix_v_sobel_2_2_2_i_fu_569_p2 = (pix_v_sobel_2_2_1_i_fu_563_p2 - tmp_23_2_2_cast_i_fu_534_p1);

assign pix_v_sobel_2_2_i_fu_546_p2 = (pix_v_sobel_2_1_2_ca_fu_543_p1 - tmp_23_2_cast_i_fu_524_p1);

assign r_V_1_fu_708_p2 = mantissa_V_1_i_i_i_c_fu_650_p1 << tmp_i_i_i_i_96_fu_698_p1;

assign r_V_fu_702_p2 = mantissa_V_fu_640_p4 >> sh_assign_2_i_i_i_ca_1_fu_694_p1;

assign result_V_1_fu_744_p2 = (32'd0 - p_Val2_5_reg_1060);

assign sel_tmp1_demorgan_fu_843_p2 = (tmp_20_i_fu_793_p2 & tmp_19_i_fu_787_p2);

assign sel_tmp1_fu_849_p2 = (sel_tmp1_demorgan_fu_843_p2 ^ 1'd1);

assign sel_tmp2_fu_861_p2 = (tmp_21_i_fu_805_p2 & tmp1_fu_855_p2);

assign sel_tmp_cast_fu_873_p3 = ((not_sel_tmp2_fu_867_p2[0:0] === 1'b1) ? 2'd3 : 2'd0);

assign sh_assign_2_i_i_i_ca_1_fu_694_p1 = ush_fu_682_p3;

assign sh_assign_2_i_i_i_ca_fu_690_p1 = ush_fu_682_p3;

assign sh_assign_fu_658_p2 = ($signed(9'd385) + $signed(tmp_i_i_i_i_cast_i_fu_654_p1));

assign start_out = real_start;

assign t_int_fu_783_p1 = $signed(grp_fu_602_p2);

assign tmp1_fu_855_p2 = (tmp_22_i_fu_811_p2 & sel_tmp1_fu_849_p2);

assign tmp2_fu_351_p2 = (tmp_26_i_fu_345_p2 & icmp8_fu_339_p2);

assign tmp3_fu_306_p2 = (tmp_2_i_fu_300_p2 & icmp_fu_294_p2);

assign tmp_10_fu_329_p4 = {{xi_i_reg_242[9:2]}};

assign tmp_10_i_fu_896_p0 = pix_h_sobel_2_2_2_ca_fu_585_p1;

assign tmp_10_i_fu_896_p1 = pix_h_sobel_2_2_2_ca_fu_585_p1;

assign tmp_11_fu_771_p1 = p_Val2_6_fu_749_p3[7:0];

assign tmp_16_i_fu_575_p2 = ((pix_h_sobel_2_2_1_i_fu_528_p2 == tmp_23_2_2_cast_i_fu_534_p1) ? 1'b1 : 1'b0);

assign tmp_19_i_fu_787_p2 = (($signed(ap_phi_reg_pp0_iter27_t_int1_i_reg_253) > $signed(32'd4294966678)) ? 1'b1 : 1'b0);

assign tmp_1_fu_881_p2 = (sel_tmp2_fu_861_p2 | or_cond_i_fu_799_p2);

assign tmp_20_i_fu_793_p2 = (($signed(ap_phi_reg_pp0_iter27_t_int1_i_reg_253) < $signed(32'd4294967191)) ? 1'b1 : 1'b0);

assign tmp_21_i_fu_805_p2 = (($signed(ap_phi_reg_pp0_iter27_t_int1_i_reg_253) > $signed(32'd4294967190)) ? 1'b1 : 1'b0);

assign tmp_22_i_fu_811_p2 = (($signed(ap_phi_reg_pp0_iter27_t_int1_i_reg_253) < $signed(32'd107)) ? 1'b1 : 1'b0);

assign tmp_23_0_2_cast9_i_c_fu_420_p1 = window_buf_0_2_fu_377_p4;

assign tmp_23_0_cast10_i_ca_fu_416_p1 = window_buf_0_1_fu_166;

assign tmp_23_2_2_cast_i_fu_534_p1 = window_buf_2_2_reg_989;

assign tmp_23_2_cast_i_fu_524_p1 = window_buf_2_1_fu_182;

assign tmp_23_i_fu_817_p2 = (($signed(ap_phi_reg_pp0_iter27_t_int1_i_reg_253) > $signed(32'd106)) ? 1'b1 : 1'b0);

assign tmp_24_1_cast_i_fu_442_p1 = tmp_24_1_i_fu_434_p3;

assign tmp_24_1_i_fu_434_p3 = {{window_buf_1_1_fu_174}, {1'd0}};

assign tmp_24_i_fu_823_p2 = (($signed(ap_phi_reg_pp0_iter27_t_int1_i_reg_253) < $signed(32'd618)) ? 1'b1 : 1'b0);

assign tmp_25_tr_i_fu_588_p3 = {{pix_v_sobel_2_2_2_i_reg_1010}, {8'd0}};

assign tmp_26_i_fu_345_p2 = ((xi_i_reg_242 < 10'd509) ? 1'b1 : 1'b0);

assign tmp_28_i_fu_775_p3 = ((icmp5_fu_765_p2[0:0] === 1'b1) ? 8'd255 : tmp_11_fu_771_p1);

assign tmp_2_fu_284_p4 = {{yi_i_reg_231[9:2]}};

assign tmp_2_i_fu_300_p2 = ((yi_i_reg_231 < 10'd509) ? 1'b1 : 1'b0);

assign tmp_30_0_1_cast_i_fu_460_p1 = tmp_30_0_1_i_fu_452_p3;

assign tmp_30_0_1_i_fu_452_p3 = {{window_buf_0_1_1_fu_170}, {1'd0}};

assign tmp_3_i_fu_312_p2 = ((xi_i_reg_242 == 10'd512) ? 1'b1 : 1'b0);

assign tmp_4_fu_722_p1 = tmp_8_fu_714_p3;

assign tmp_4_i_fu_324_p1 = xi_i_reg_242;

assign tmp_5_fu_726_p4 = {{r_V_1_fu_708_p2[55:24]}};

assign tmp_8_fu_714_p3 = r_V_fu_702_p2[32'd24];

assign tmp_8_i_fu_397_p4 = {{line_buf_q0[23:8]}};

assign tmp_9_fu_755_p4 = {{p_Val2_6_fu_749_p3[31:8]}};

assign tmp_V_1_fu_636_p1 = p_Val2_s_fu_615_p1[22:0];

assign tmp_V_fu_626_p4 = {{p_Val2_s_fu_615_p1[30:23]}};

assign tmp_cast_fu_470_p1 = tmp_fu_464_p2;

assign tmp_fu_464_p2 = (tmp_23_0_cast10_i_ca_fu_416_p1 + tmp_23_0_2_cast9_i_c_fu_420_p1);

assign tmp_i_fu_272_p2 = ((yi_i_reg_231 == 10'd512) ? 1'b1 : 1'b0);

assign tmp_i_i_i_cast_i_fu_678_p1 = $signed(tmp_i_i_i_i_fu_672_p2);

assign tmp_i_i_i_i_96_fu_698_p1 = $unsigned(sh_assign_2_i_i_i_ca_fu_690_p1);

assign tmp_i_i_i_i_cast_i_fu_654_p1 = tmp_V_fu_626_p4;

assign tmp_i_i_i_i_fu_672_p2 = (8'd127 - tmp_V_fu_626_p4);

assign ush_fu_682_p3 = ((isNeg_fu_664_p3[0:0] === 1'b1) ? tmp_i_i_i_cast_i_fu_678_p1 : sh_assign_fu_658_p2);

assign window_buf_0_2_fu_377_p4 = {{line_buf_q0[15:8]}};

assign xi_fu_318_p2 = (xi_i_reg_242 + 10'd1);

assign yi_fu_278_p2 = (yi_i_reg_231 + 10'd1);

endmodule //Sobel_512u_512u_s
