#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("s_axi_CONTROL_BUS_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_AWADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_ARADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CONTROL_BUS_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_aclk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n_s_axi_aclk", 1, hls_in, -1, "", "", 1),
	Port_Property("axis_in_TDATA", 24, hls_in, 0, "axis", "in_data", 1),
	Port_Property("axis_in_TUSER", 1, hls_in, 1, "axis", "in_data", 1),
	Port_Property("axis_in_TLAST", 1, hls_in, 2, "axis", "in_data", 1),
	Port_Property("axis_out_TDATA", 24, hls_out, 3, "axis", "out_data", 1),
	Port_Property("axis_out_TUSER", 1, hls_out, 4, "axis", "out_data", 1),
	Port_Property("axis_out_TLAST", 1, hls_out, 5, "axis", "out_data", 1),
	Port_Property("axis_in_TVALID", 1, hls_in, 2, "axis", "in_vld", 1),
	Port_Property("axis_in_TREADY", 1, hls_out, 2, "axis", "in_acc", 1),
	Port_Property("axis_out_TVALID", 1, hls_out, 5, "axis", "out_vld", 1),
	Port_Property("axis_out_TREADY", 1, hls_in, 5, "axis", "out_acc", 1),
};
const char* HLS_Design_Meta::dut_name = "canny_edge_detection";
