// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "GrayArray2AXIS.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic GrayArray2AXIS::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic GrayArray2AXIS::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> GrayArray2AXIS::ap_ST_fsm_state1 = "1";
const sc_lv<4> GrayArray2AXIS::ap_ST_fsm_state2 = "10";
const sc_lv<4> GrayArray2AXIS::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> GrayArray2AXIS::ap_ST_fsm_state6 = "1000";
const sc_lv<32> GrayArray2AXIS::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool GrayArray2AXIS::ap_const_boolean_1 = true;
const sc_lv<1> GrayArray2AXIS::ap_const_lv1_0 = "0";
const sc_lv<1> GrayArray2AXIS::ap_const_lv1_1 = "1";
const sc_lv<2> GrayArray2AXIS::ap_const_lv2_0 = "00";
const sc_lv<2> GrayArray2AXIS::ap_const_lv2_2 = "10";
const sc_lv<2> GrayArray2AXIS::ap_const_lv2_3 = "11";
const sc_lv<2> GrayArray2AXIS::ap_const_lv2_1 = "1";
const sc_lv<32> GrayArray2AXIS::ap_const_lv32_2 = "10";
const bool GrayArray2AXIS::ap_const_boolean_0 = false;
const sc_lv<32> GrayArray2AXIS::ap_const_lv32_1 = "1";
const sc_lv<10> GrayArray2AXIS::ap_const_lv10_0 = "0000000000";
const sc_lv<32> GrayArray2AXIS::ap_const_lv32_3 = "11";
const sc_lv<10> GrayArray2AXIS::ap_const_lv10_200 = "1000000000";
const sc_lv<10> GrayArray2AXIS::ap_const_lv10_1 = "1";
const sc_lv<9> GrayArray2AXIS::ap_const_lv9_0 = "000000000";
const sc_lv<10> GrayArray2AXIS::ap_const_lv10_1FF = "111111111";

GrayArray2AXIS::GrayArray2AXIS(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( fifo7_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_59_i_reg_181 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( fifo7_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_59_i_reg_181 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_state4_io );
    sensitive << ( ap_block_state5_io );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( fifo7_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_59_i_reg_181 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_state4_io );
    sensitive << ( ap_block_state5_io );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( axis_dst_V_data_V_1_ack_in );
    sensitive << ( axis_dst_V_user_V_1_ack_in );
    sensitive << ( axis_dst_V_last_V_1_ack_in );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_io);
    sensitive << ( axis_dst_V_data_V_1_ack_in );
    sensitive << ( tmp_59_i_reg_181 );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( fifo7_empty_n );
    sensitive << ( tmp_59_i_reg_181 );

    SC_METHOD(thread_ap_block_state5_io);
    sensitive << ( axis_dst_V_data_V_1_ack_in );
    sensitive << ( tmp_59_i_reg_181_pp0_iter1_reg );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( tmp_59_i_fu_127_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( axis_dst_V_data_V_1_ack_in );
    sensitive << ( axis_dst_V_user_V_1_ack_in );
    sensitive << ( axis_dst_V_last_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_i_fu_111_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( axis_dst_V_data_V_1_ack_in );
    sensitive << ( axis_dst_V_user_V_1_ack_in );
    sensitive << ( axis_dst_V_last_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_i_fu_111_p2 );

    SC_METHOD(thread_axis_dst_V_data_V_1_ack_in);
    sensitive << ( axis_dst_V_data_V_1_state );

    SC_METHOD(thread_axis_dst_V_data_V_1_ack_out);
    sensitive << ( axis_out_TREADY );

    SC_METHOD(thread_axis_dst_V_data_V_1_data_out);
    sensitive << ( axis_dst_V_data_V_1_payload_A );
    sensitive << ( axis_dst_V_data_V_1_payload_B );
    sensitive << ( axis_dst_V_data_V_1_sel );

    SC_METHOD(thread_axis_dst_V_data_V_1_load_A);
    sensitive << ( axis_dst_V_data_V_1_sel_wr );
    sensitive << ( axis_dst_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_axis_dst_V_data_V_1_load_B);
    sensitive << ( axis_dst_V_data_V_1_sel_wr );
    sensitive << ( axis_dst_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_axis_dst_V_data_V_1_sel);
    sensitive << ( axis_dst_V_data_V_1_sel_rd );

    SC_METHOD(thread_axis_dst_V_data_V_1_state_cmp_full);
    sensitive << ( axis_dst_V_data_V_1_state );

    SC_METHOD(thread_axis_dst_V_data_V_1_vld_in);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_59_i_reg_181 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_axis_dst_V_data_V_1_vld_out);
    sensitive << ( axis_dst_V_data_V_1_state );

    SC_METHOD(thread_axis_dst_V_last_V_1_ack_in);
    sensitive << ( axis_dst_V_last_V_1_state );

    SC_METHOD(thread_axis_dst_V_last_V_1_ack_out);
    sensitive << ( axis_out_TREADY );

    SC_METHOD(thread_axis_dst_V_last_V_1_data_out);
    sensitive << ( axis_dst_V_last_V_1_payload_A );
    sensitive << ( axis_dst_V_last_V_1_payload_B );
    sensitive << ( axis_dst_V_last_V_1_sel );

    SC_METHOD(thread_axis_dst_V_last_V_1_load_A);
    sensitive << ( axis_dst_V_last_V_1_sel_wr );
    sensitive << ( axis_dst_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_axis_dst_V_last_V_1_load_B);
    sensitive << ( axis_dst_V_last_V_1_sel_wr );
    sensitive << ( axis_dst_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_axis_dst_V_last_V_1_sel);
    sensitive << ( axis_dst_V_last_V_1_sel_rd );

    SC_METHOD(thread_axis_dst_V_last_V_1_state_cmp_full);
    sensitive << ( axis_dst_V_last_V_1_state );

    SC_METHOD(thread_axis_dst_V_last_V_1_vld_in);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_59_i_reg_181 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_axis_dst_V_last_V_1_vld_out);
    sensitive << ( axis_dst_V_last_V_1_state );

    SC_METHOD(thread_axis_dst_V_user_V_1_ack_in);
    sensitive << ( axis_dst_V_user_V_1_state );

    SC_METHOD(thread_axis_dst_V_user_V_1_ack_out);
    sensitive << ( axis_out_TREADY );

    SC_METHOD(thread_axis_dst_V_user_V_1_data_out);
    sensitive << ( axis_dst_V_user_V_1_payload_A );
    sensitive << ( axis_dst_V_user_V_1_payload_B );
    sensitive << ( axis_dst_V_user_V_1_sel );

    SC_METHOD(thread_axis_dst_V_user_V_1_load_A);
    sensitive << ( axis_dst_V_user_V_1_sel_wr );
    sensitive << ( axis_dst_V_user_V_1_state_cmp_full );

    SC_METHOD(thread_axis_dst_V_user_V_1_load_B);
    sensitive << ( axis_dst_V_user_V_1_sel_wr );
    sensitive << ( axis_dst_V_user_V_1_state_cmp_full );

    SC_METHOD(thread_axis_dst_V_user_V_1_sel);
    sensitive << ( axis_dst_V_user_V_1_sel_rd );

    SC_METHOD(thread_axis_dst_V_user_V_1_state_cmp_full);
    sensitive << ( axis_dst_V_user_V_1_state );

    SC_METHOD(thread_axis_dst_V_user_V_1_vld_in);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_59_i_reg_181 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_axis_dst_V_user_V_1_vld_out);
    sensitive << ( axis_dst_V_user_V_1_state );

    SC_METHOD(thread_axis_out_TDATA);
    sensitive << ( axis_dst_V_data_V_1_data_out );

    SC_METHOD(thread_axis_out_TDATA_blk_n);
    sensitive << ( axis_dst_V_data_V_1_state );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_59_i_reg_181 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_59_i_reg_181_pp0_iter1_reg );

    SC_METHOD(thread_axis_out_TLAST);
    sensitive << ( axis_dst_V_last_V_1_data_out );

    SC_METHOD(thread_axis_out_TUSER);
    sensitive << ( axis_dst_V_user_V_1_data_out );

    SC_METHOD(thread_axis_out_TVALID);
    sensitive << ( axis_dst_V_last_V_1_state );

    SC_METHOD(thread_axis_writer_data_V_fu_156_p4);
    sensitive << ( fifo7_dout );

    SC_METHOD(thread_fifo7_blk_n);
    sensitive << ( fifo7_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_59_i_reg_181 );

    SC_METHOD(thread_fifo7_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_59_i_reg_181 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp_14_fu_123_p1);
    sensitive << ( xi_i_reg_96 );

    SC_METHOD(thread_tmp_59_i_fu_127_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( xi_i_reg_96 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_63_i_fu_139_p2);
    sensitive << ( tmp_reg_167 );
    sensitive << ( tmp_14_fu_123_p1 );

    SC_METHOD(thread_tmp_fu_107_p1);
    sensitive << ( yi_i_reg_85 );

    SC_METHOD(thread_tmp_i_fu_111_p2);
    sensitive << ( axis_dst_V_data_V_1_ack_in );
    sensitive << ( axis_dst_V_user_V_1_ack_in );
    sensitive << ( axis_dst_V_last_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( yi_i_reg_85 );

    SC_METHOD(thread_tmp_last_V_fu_150_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( xi_i_reg_96 );
    sensitive << ( tmp_59_i_fu_127_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_user_V_fu_144_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_59_i_fu_127_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_63_i_fu_139_p2 );

    SC_METHOD(thread_xi_fu_133_p2);
    sensitive << ( xi_i_reg_96 );

    SC_METHOD(thread_yi_fu_117_p2);
    sensitive << ( yi_i_reg_85 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( axis_dst_V_data_V_1_ack_in );
    sensitive << ( axis_dst_V_user_V_1_ack_in );
    sensitive << ( axis_dst_V_last_V_1_ack_in );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_i_fu_111_p2 );
    sensitive << ( tmp_59_i_fu_127_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    axis_dst_V_data_V_1_sel_rd = SC_LOGIC_0;
    axis_dst_V_data_V_1_sel_wr = SC_LOGIC_0;
    axis_dst_V_data_V_1_state = "00";
    axis_dst_V_user_V_1_sel_rd = SC_LOGIC_0;
    axis_dst_V_user_V_1_sel_wr = SC_LOGIC_0;
    axis_dst_V_user_V_1_state = "00";
    axis_dst_V_last_V_1_sel_rd = SC_LOGIC_0;
    axis_dst_V_last_V_1_sel_wr = SC_LOGIC_0;
    axis_dst_V_last_V_1_state = "00";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "GrayArray2AXIS_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, axis_out_TDATA, "(port)axis_out_TDATA");
    sc_trace(mVcdFile, axis_out_TVALID, "(port)axis_out_TVALID");
    sc_trace(mVcdFile, axis_out_TREADY, "(port)axis_out_TREADY");
    sc_trace(mVcdFile, axis_out_TUSER, "(port)axis_out_TUSER");
    sc_trace(mVcdFile, axis_out_TLAST, "(port)axis_out_TLAST");
    sc_trace(mVcdFile, fifo7_dout, "(port)fifo7_dout");
    sc_trace(mVcdFile, fifo7_empty_n, "(port)fifo7_empty_n");
    sc_trace(mVcdFile, fifo7_read, "(port)fifo7_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_data_out, "axis_dst_V_data_V_1_data_out");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_vld_in, "axis_dst_V_data_V_1_vld_in");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_vld_out, "axis_dst_V_data_V_1_vld_out");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_ack_in, "axis_dst_V_data_V_1_ack_in");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_ack_out, "axis_dst_V_data_V_1_ack_out");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_payload_A, "axis_dst_V_data_V_1_payload_A");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_payload_B, "axis_dst_V_data_V_1_payload_B");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_sel_rd, "axis_dst_V_data_V_1_sel_rd");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_sel_wr, "axis_dst_V_data_V_1_sel_wr");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_sel, "axis_dst_V_data_V_1_sel");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_load_A, "axis_dst_V_data_V_1_load_A");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_load_B, "axis_dst_V_data_V_1_load_B");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_state, "axis_dst_V_data_V_1_state");
    sc_trace(mVcdFile, axis_dst_V_data_V_1_state_cmp_full, "axis_dst_V_data_V_1_state_cmp_full");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_data_out, "axis_dst_V_user_V_1_data_out");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_vld_in, "axis_dst_V_user_V_1_vld_in");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_vld_out, "axis_dst_V_user_V_1_vld_out");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_ack_in, "axis_dst_V_user_V_1_ack_in");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_ack_out, "axis_dst_V_user_V_1_ack_out");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_payload_A, "axis_dst_V_user_V_1_payload_A");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_payload_B, "axis_dst_V_user_V_1_payload_B");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_sel_rd, "axis_dst_V_user_V_1_sel_rd");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_sel_wr, "axis_dst_V_user_V_1_sel_wr");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_sel, "axis_dst_V_user_V_1_sel");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_load_A, "axis_dst_V_user_V_1_load_A");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_load_B, "axis_dst_V_user_V_1_load_B");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_state, "axis_dst_V_user_V_1_state");
    sc_trace(mVcdFile, axis_dst_V_user_V_1_state_cmp_full, "axis_dst_V_user_V_1_state_cmp_full");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_data_out, "axis_dst_V_last_V_1_data_out");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_vld_in, "axis_dst_V_last_V_1_vld_in");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_vld_out, "axis_dst_V_last_V_1_vld_out");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_ack_in, "axis_dst_V_last_V_1_ack_in");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_ack_out, "axis_dst_V_last_V_1_ack_out");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_payload_A, "axis_dst_V_last_V_1_payload_A");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_payload_B, "axis_dst_V_last_V_1_payload_B");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_sel_rd, "axis_dst_V_last_V_1_sel_rd");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_sel_wr, "axis_dst_V_last_V_1_sel_wr");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_sel, "axis_dst_V_last_V_1_sel");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_load_A, "axis_dst_V_last_V_1_load_A");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_load_B, "axis_dst_V_last_V_1_load_B");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_state, "axis_dst_V_last_V_1_state");
    sc_trace(mVcdFile, axis_dst_V_last_V_1_state_cmp_full, "axis_dst_V_last_V_1_state_cmp_full");
    sc_trace(mVcdFile, axis_out_TDATA_blk_n, "axis_out_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_59_i_reg_181, "tmp_59_i_reg_181");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, tmp_59_i_reg_181_pp0_iter1_reg, "tmp_59_i_reg_181_pp0_iter1_reg");
    sc_trace(mVcdFile, fifo7_blk_n, "fifo7_blk_n");
    sc_trace(mVcdFile, xi_i_reg_96, "xi_i_reg_96");
    sc_trace(mVcdFile, tmp_fu_107_p1, "tmp_fu_107_p1");
    sc_trace(mVcdFile, tmp_reg_167, "tmp_reg_167");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, tmp_i_fu_111_p2, "tmp_i_fu_111_p2");
    sc_trace(mVcdFile, yi_fu_117_p2, "yi_fu_117_p2");
    sc_trace(mVcdFile, yi_reg_176, "yi_reg_176");
    sc_trace(mVcdFile, tmp_59_i_fu_127_p2, "tmp_59_i_fu_127_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_io, "ap_block_state4_io");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_io, "ap_block_state5_io");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, xi_fu_133_p2, "xi_fu_133_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_user_V_fu_144_p2, "tmp_user_V_fu_144_p2");
    sc_trace(mVcdFile, tmp_user_V_reg_190, "tmp_user_V_reg_190");
    sc_trace(mVcdFile, tmp_last_V_fu_150_p2, "tmp_last_V_fu_150_p2");
    sc_trace(mVcdFile, tmp_last_V_reg_195, "tmp_last_V_reg_195");
    sc_trace(mVcdFile, axis_writer_data_V_fu_156_p4, "axis_writer_data_V_fu_156_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, yi_i_reg_85, "yi_i_reg_85");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, tmp_14_fu_123_p1, "tmp_14_fu_123_p1");
    sc_trace(mVcdFile, tmp_63_i_fu_139_p2, "tmp_63_i_fu_139_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

GrayArray2AXIS::~GrayArray2AXIS() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void GrayArray2AXIS::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_in.read())) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_fu_111_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_in.read())) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_111_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_in.read())) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_111_p2.read()))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        axis_dst_V_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_vld_out.read()))) {
            axis_dst_V_data_V_1_sel_rd =  (sc_logic) (~axis_dst_V_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        axis_dst_V_data_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_ack_in.read()))) {
            axis_dst_V_data_V_1_sel_wr =  (sc_logic) (~axis_dst_V_data_V_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        axis_dst_V_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(axis_dst_V_data_V_1_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(axis_dst_V_data_V_1_state.read(), ap_const_lv2_2)))) {
            axis_dst_V_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(axis_dst_V_data_V_1_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(axis_dst_V_data_V_1_state.read(), ap_const_lv2_1)))) {
            axis_dst_V_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(axis_dst_V_data_V_1_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(axis_dst_V_data_V_1_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(axis_dst_V_data_V_1_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_ack_out.read()))))) {
            axis_dst_V_data_V_1_state = ap_const_lv2_3;
        } else {
            axis_dst_V_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        axis_dst_V_last_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_vld_out.read()))) {
            axis_dst_V_last_V_1_sel_rd =  (sc_logic) (~axis_dst_V_last_V_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        axis_dst_V_last_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_ack_in.read()))) {
            axis_dst_V_last_V_1_sel_wr =  (sc_logic) (~axis_dst_V_last_V_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        axis_dst_V_last_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, axis_dst_V_last_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, axis_dst_V_last_V_1_state.read())))) {
            axis_dst_V_last_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, axis_dst_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, axis_dst_V_last_V_1_state.read())))) {
            axis_dst_V_last_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, axis_dst_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, axis_dst_V_last_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, axis_dst_V_last_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_ack_out.read()))))) {
            axis_dst_V_last_V_1_state = ap_const_lv2_3;
        } else {
            axis_dst_V_last_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        axis_dst_V_user_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_vld_out.read()))) {
            axis_dst_V_user_V_1_sel_rd =  (sc_logic) (~axis_dst_V_user_V_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        axis_dst_V_user_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_ack_in.read()))) {
            axis_dst_V_user_V_1_sel_wr =  (sc_logic) (~axis_dst_V_user_V_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        axis_dst_V_user_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, axis_dst_V_user_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, axis_dst_V_user_V_1_state.read())))) {
            axis_dst_V_user_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, axis_dst_V_user_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, axis_dst_V_user_V_1_state.read())))) {
            axis_dst_V_user_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, axis_dst_V_user_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, axis_dst_V_user_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, axis_dst_V_user_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_ack_out.read()))))) {
            axis_dst_V_user_V_1_state = ap_const_lv2_3;
        } else {
            axis_dst_V_user_V_1_state = ap_const_lv2_2;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_in.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_111_p2.read()))) {
        xi_i_reg_96 = ap_const_lv10_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_fu_127_p2.read()))) {
        xi_i_reg_96 = xi_fu_133_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        yi_i_reg_85 = yi_reg_176.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        yi_i_reg_85 = ap_const_lv10_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_load_A.read())) {
        axis_dst_V_data_V_1_payload_A = axis_writer_data_V_fu_156_p4.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_load_B.read())) {
        axis_dst_V_data_V_1_payload_B = axis_writer_data_V_fu_156_p4.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_load_A.read())) {
        axis_dst_V_last_V_1_payload_A = tmp_last_V_reg_195.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_load_B.read())) {
        axis_dst_V_last_V_1_payload_B = tmp_last_V_reg_195.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_load_A.read())) {
        axis_dst_V_user_V_1_payload_A = tmp_user_V_reg_190.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_load_B.read())) {
        axis_dst_V_user_V_1_payload_B = tmp_user_V_reg_190.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_59_i_reg_181 = tmp_59_i_fu_127_p2.read();
        tmp_59_i_reg_181_pp0_iter1_reg = tmp_59_i_reg_181.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_fu_127_p2.read()))) {
        tmp_last_V_reg_195 = tmp_last_V_fu_150_p2.read();
        tmp_user_V_reg_190 = tmp_user_V_fu_144_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_in.read())))) {
        tmp_reg_167 = tmp_fu_107_p1.read();
        yi_reg_176 = yi_fu_117_p2.read();
    }
}

void GrayArray2AXIS::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void GrayArray2AXIS::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void GrayArray2AXIS::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void GrayArray2AXIS::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[3];
}

void GrayArray2AXIS::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void GrayArray2AXIS::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181.read()) && esl_seteq<1,1,1>(ap_const_logic_0, fifo7_empty_n.read()));
}

void GrayArray2AXIS::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo7_empty_n.read())) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state4_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state5_io.read())));
}

void GrayArray2AXIS::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo7_empty_n.read())) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state4_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state5_io.read())));
}

void GrayArray2AXIS::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void GrayArray2AXIS::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_in.read()));
}

void GrayArray2AXIS::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void GrayArray2AXIS::thread_ap_block_state4_io() {
    ap_block_state4_io = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181.read()) && esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()));
}

void GrayArray2AXIS::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181.read()) && esl_seteq<1,1,1>(ap_const_logic_0, fifo7_empty_n.read()));
}

void GrayArray2AXIS::thread_ap_block_state5_io() {
    ap_block_state5_io = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()));
}

void GrayArray2AXIS::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void GrayArray2AXIS::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_59_i_fu_127_p2.read())) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void GrayArray2AXIS::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_in.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_fu_111_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void GrayArray2AXIS::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void GrayArray2AXIS::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void GrayArray2AXIS::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void GrayArray2AXIS::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_in.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_fu_111_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void GrayArray2AXIS::thread_axis_dst_V_data_V_1_ack_in() {
    axis_dst_V_data_V_1_ack_in = axis_dst_V_data_V_1_state.read()[1];
}

void GrayArray2AXIS::thread_axis_dst_V_data_V_1_ack_out() {
    axis_dst_V_data_V_1_ack_out = axis_out_TREADY.read();
}

void GrayArray2AXIS::thread_axis_dst_V_data_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_data_V_1_sel.read())) {
        axis_dst_V_data_V_1_data_out = axis_dst_V_data_V_1_payload_B.read();
    } else {
        axis_dst_V_data_V_1_data_out = axis_dst_V_data_V_1_payload_A.read();
    }
}

void GrayArray2AXIS::thread_axis_dst_V_data_V_1_load_A() {
    axis_dst_V_data_V_1_load_A = (axis_dst_V_data_V_1_state_cmp_full.read() & ~axis_dst_V_data_V_1_sel_wr.read());
}

void GrayArray2AXIS::thread_axis_dst_V_data_V_1_load_B() {
    axis_dst_V_data_V_1_load_B = (axis_dst_V_data_V_1_sel_wr.read() & axis_dst_V_data_V_1_state_cmp_full.read());
}

void GrayArray2AXIS::thread_axis_dst_V_data_V_1_sel() {
    axis_dst_V_data_V_1_sel = axis_dst_V_data_V_1_sel_rd.read();
}

void GrayArray2AXIS::thread_axis_dst_V_data_V_1_state_cmp_full() {
    axis_dst_V_data_V_1_state_cmp_full =  (sc_logic) ((!axis_dst_V_data_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(axis_dst_V_data_V_1_state.read() != ap_const_lv2_1))[0];
}

void GrayArray2AXIS::thread_axis_dst_V_data_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        axis_dst_V_data_V_1_vld_in = ap_const_logic_1;
    } else {
        axis_dst_V_data_V_1_vld_in = ap_const_logic_0;
    }
}

void GrayArray2AXIS::thread_axis_dst_V_data_V_1_vld_out() {
    axis_dst_V_data_V_1_vld_out = axis_dst_V_data_V_1_state.read()[0];
}

void GrayArray2AXIS::thread_axis_dst_V_last_V_1_ack_in() {
    axis_dst_V_last_V_1_ack_in = axis_dst_V_last_V_1_state.read()[1];
}

void GrayArray2AXIS::thread_axis_dst_V_last_V_1_ack_out() {
    axis_dst_V_last_V_1_ack_out = axis_out_TREADY.read();
}

void GrayArray2AXIS::thread_axis_dst_V_last_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_last_V_1_sel.read())) {
        axis_dst_V_last_V_1_data_out = axis_dst_V_last_V_1_payload_B.read();
    } else {
        axis_dst_V_last_V_1_data_out = axis_dst_V_last_V_1_payload_A.read();
    }
}

void GrayArray2AXIS::thread_axis_dst_V_last_V_1_load_A() {
    axis_dst_V_last_V_1_load_A = (axis_dst_V_last_V_1_state_cmp_full.read() & ~axis_dst_V_last_V_1_sel_wr.read());
}

void GrayArray2AXIS::thread_axis_dst_V_last_V_1_load_B() {
    axis_dst_V_last_V_1_load_B = (axis_dst_V_last_V_1_sel_wr.read() & axis_dst_V_last_V_1_state_cmp_full.read());
}

void GrayArray2AXIS::thread_axis_dst_V_last_V_1_sel() {
    axis_dst_V_last_V_1_sel = axis_dst_V_last_V_1_sel_rd.read();
}

void GrayArray2AXIS::thread_axis_dst_V_last_V_1_state_cmp_full() {
    axis_dst_V_last_V_1_state_cmp_full =  (sc_logic) ((!axis_dst_V_last_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(axis_dst_V_last_V_1_state.read() != ap_const_lv2_1))[0];
}

void GrayArray2AXIS::thread_axis_dst_V_last_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        axis_dst_V_last_V_1_vld_in = ap_const_logic_1;
    } else {
        axis_dst_V_last_V_1_vld_in = ap_const_logic_0;
    }
}

void GrayArray2AXIS::thread_axis_dst_V_last_V_1_vld_out() {
    axis_dst_V_last_V_1_vld_out = axis_dst_V_last_V_1_state.read()[0];
}

void GrayArray2AXIS::thread_axis_dst_V_user_V_1_ack_in() {
    axis_dst_V_user_V_1_ack_in = axis_dst_V_user_V_1_state.read()[1];
}

void GrayArray2AXIS::thread_axis_dst_V_user_V_1_ack_out() {
    axis_dst_V_user_V_1_ack_out = axis_out_TREADY.read();
}

void GrayArray2AXIS::thread_axis_dst_V_user_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, axis_dst_V_user_V_1_sel.read())) {
        axis_dst_V_user_V_1_data_out = axis_dst_V_user_V_1_payload_B.read();
    } else {
        axis_dst_V_user_V_1_data_out = axis_dst_V_user_V_1_payload_A.read();
    }
}

void GrayArray2AXIS::thread_axis_dst_V_user_V_1_load_A() {
    axis_dst_V_user_V_1_load_A = (axis_dst_V_user_V_1_state_cmp_full.read() & ~axis_dst_V_user_V_1_sel_wr.read());
}

void GrayArray2AXIS::thread_axis_dst_V_user_V_1_load_B() {
    axis_dst_V_user_V_1_load_B = (axis_dst_V_user_V_1_sel_wr.read() & axis_dst_V_user_V_1_state_cmp_full.read());
}

void GrayArray2AXIS::thread_axis_dst_V_user_V_1_sel() {
    axis_dst_V_user_V_1_sel = axis_dst_V_user_V_1_sel_rd.read();
}

void GrayArray2AXIS::thread_axis_dst_V_user_V_1_state_cmp_full() {
    axis_dst_V_user_V_1_state_cmp_full =  (sc_logic) ((!axis_dst_V_user_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(axis_dst_V_user_V_1_state.read() != ap_const_lv2_1))[0];
}

void GrayArray2AXIS::thread_axis_dst_V_user_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        axis_dst_V_user_V_1_vld_in = ap_const_logic_1;
    } else {
        axis_dst_V_user_V_1_vld_in = ap_const_logic_0;
    }
}

void GrayArray2AXIS::thread_axis_dst_V_user_V_1_vld_out() {
    axis_dst_V_user_V_1_vld_out = axis_dst_V_user_V_1_state.read()[0];
}

void GrayArray2AXIS::thread_axis_out_TDATA() {
    axis_out_TDATA = axis_dst_V_data_V_1_data_out.read();
}

void GrayArray2AXIS::thread_axis_out_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181_pp0_iter1_reg.read())))) {
        axis_out_TDATA_blk_n = axis_dst_V_data_V_1_state.read()[1];
    } else {
        axis_out_TDATA_blk_n = ap_const_logic_1;
    }
}

void GrayArray2AXIS::thread_axis_out_TLAST() {
    axis_out_TLAST = axis_dst_V_last_V_1_data_out.read();
}

void GrayArray2AXIS::thread_axis_out_TUSER() {
    axis_out_TUSER = axis_dst_V_user_V_1_data_out.read();
}

void GrayArray2AXIS::thread_axis_out_TVALID() {
    axis_out_TVALID = axis_dst_V_last_V_1_state.read()[0];
}

void GrayArray2AXIS::thread_axis_writer_data_V_fu_156_p4() {
    axis_writer_data_V_fu_156_p4 = esl_concat<16,8>(esl_concat<8,8>(fifo7_dout.read(), fifo7_dout.read()), fifo7_dout.read());
}

void GrayArray2AXIS::thread_fifo7_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181.read()))) {
        fifo7_blk_n = fifo7_empty_n.read();
    } else {
        fifo7_blk_n = ap_const_logic_1;
    }
}

void GrayArray2AXIS::thread_fifo7_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_59_i_reg_181.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        fifo7_read = ap_const_logic_1;
    } else {
        fifo7_read = ap_const_logic_0;
    }
}

void GrayArray2AXIS::thread_tmp_14_fu_123_p1() {
    tmp_14_fu_123_p1 = xi_i_reg_96.read().range(9-1, 0);
}

void GrayArray2AXIS::thread_tmp_59_i_fu_127_p2() {
    tmp_59_i_fu_127_p2 = (!xi_i_reg_96.read().is_01() || !ap_const_lv10_200.is_01())? sc_lv<1>(): sc_lv<1>(xi_i_reg_96.read() == ap_const_lv10_200);
}

void GrayArray2AXIS::thread_tmp_63_i_fu_139_p2() {
    tmp_63_i_fu_139_p2 = (tmp_14_fu_123_p1.read() | tmp_reg_167.read());
}

void GrayArray2AXIS::thread_tmp_fu_107_p1() {
    tmp_fu_107_p1 = yi_i_reg_85.read().range(9-1, 0);
}

void GrayArray2AXIS::thread_tmp_i_fu_111_p2() {
    tmp_i_fu_111_p2 = (!yi_i_reg_85.read().is_01() || !ap_const_lv10_200.is_01())? sc_lv<1>(): sc_lv<1>(yi_i_reg_85.read() == ap_const_lv10_200);
}

void GrayArray2AXIS::thread_tmp_last_V_fu_150_p2() {
    tmp_last_V_fu_150_p2 = (!xi_i_reg_96.read().is_01() || !ap_const_lv10_1FF.is_01())? sc_lv<1>(): sc_lv<1>(xi_i_reg_96.read() == ap_const_lv10_1FF);
}

void GrayArray2AXIS::thread_tmp_user_V_fu_144_p2() {
    tmp_user_V_fu_144_p2 = (!tmp_63_i_fu_139_p2.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_63_i_fu_139_p2.read() == ap_const_lv9_0);
}

void GrayArray2AXIS::thread_xi_fu_133_p2() {
    xi_fu_133_p2 = (!ap_const_lv10_1.is_01() || !xi_i_reg_96.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_1) + sc_biguint<10>(xi_i_reg_96.read()));
}

void GrayArray2AXIS::thread_yi_fu_117_p2() {
    yi_fu_117_p2 = (!ap_const_lv10_1.is_01() || !yi_i_reg_85.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_1) + sc_biguint<10>(yi_i_reg_85.read()));
}

void GrayArray2AXIS::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_in.read())) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_fu_111_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_user_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis_dst_V_last_V_1_ack_in.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_111_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_59_i_fu_127_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_59_i_fu_127_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

