// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "HystThreshold.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic HystThreshold::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic HystThreshold::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> HystThreshold::ap_ST_fsm_state1 = "1";
const sc_lv<4> HystThreshold::ap_ST_fsm_state2 = "10";
const sc_lv<4> HystThreshold::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> HystThreshold::ap_ST_fsm_state6 = "1000";
const bool HystThreshold::ap_const_boolean_1 = true;
const sc_lv<32> HystThreshold::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> HystThreshold::ap_const_lv32_2 = "10";
const bool HystThreshold::ap_const_boolean_0 = false;
const sc_lv<1> HystThreshold::ap_const_lv1_0 = "0";
const sc_lv<32> HystThreshold::ap_const_lv32_1 = "1";
const sc_lv<1> HystThreshold::ap_const_lv1_1 = "1";
const sc_lv<10> HystThreshold::ap_const_lv10_0 = "0000000000";
const sc_lv<32> HystThreshold::ap_const_lv32_3 = "11";
const sc_lv<10> HystThreshold::ap_const_lv10_200 = "1000000000";
const sc_lv<10> HystThreshold::ap_const_lv10_1 = "1";
const sc_lv<2> HystThreshold::ap_const_lv2_3 = "11";
const sc_lv<2> HystThreshold::ap_const_lv2_0 = "00";
const sc_lv<2> HystThreshold::ap_const_lv2_1 = "1";

HystThreshold::HystThreshold(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( fifo5_empty_n );
    sensitive << ( fifo6_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_54_i_i_i_reg_230 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_54_i_i_i_reg_230_pp0_iter1_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( fifo5_empty_n );
    sensitive << ( fifo6_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_54_i_i_i_reg_230 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_54_i_i_i_reg_230_pp0_iter1_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( fifo5_empty_n );
    sensitive << ( fifo6_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_54_i_i_i_reg_230 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_54_i_i_i_reg_230_pp0_iter1_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( hist_hthr_empty_n );
    sensitive << ( hist_lthr_empty_n );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( fifo5_empty_n );
    sensitive << ( tmp_54_i_i_i_reg_230 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);
    sensitive << ( fifo6_full_n );
    sensitive << ( tmp_54_i_i_i_reg_230_pp0_iter1_reg );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( tmp_54_i_i_i_fu_159_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( tmp_i_i_i_fu_147_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_fifo5_blk_n);
    sensitive << ( fifo5_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_54_i_i_i_reg_230 );

    SC_METHOD(thread_fifo5_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_54_i_i_i_reg_230 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_fifo6_blk_n);
    sensitive << ( fifo6_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_54_i_i_i_reg_230_pp0_iter1_reg );

    SC_METHOD(thread_fifo6_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_54_i_i_i_reg_230_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( pix_hyst_1_i_i_i_fu_198_p3 );

    SC_METHOD(thread_fifo6_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_54_i_i_i_reg_230_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_hist_hthr_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( hist_hthr_empty_n );

    SC_METHOD(thread_hist_hthr_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( hist_hthr_empty_n );
    sensitive << ( hist_lthr_empty_n );

    SC_METHOD(thread_hist_lthr_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( hist_lthr_empty_n );

    SC_METHOD(thread_hist_lthr_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( hist_hthr_empty_n );
    sensitive << ( hist_lthr_empty_n );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( tmp_i_i_i_fu_147_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_not_tmp_57_i_i_i_fu_181_p2);
    sensitive << ( tmp_57_i_i_i_reg_239 );

    SC_METHOD(thread_pix_hyst_1_i_i_i_fu_198_p3);
    sensitive << ( tmp_fu_194_p2 );
    sensitive << ( pix_hyst_i_i_i_cast_fu_186_p3 );

    SC_METHOD(thread_pix_hyst_i_i_i_cast_fu_186_p3);
    sensitive << ( not_tmp_57_i_i_i_fu_181_p2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_54_i_i_i_fu_159_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( xi_i_i_i_reg_136 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_57_i_i_i_fu_171_p2);
    sensitive << ( fifo5_dout );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_54_i_i_i_reg_230 );
    sensitive << ( hist_lthr_read_reg_216 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp_58_i_i_i_fu_176_p2);
    sensitive << ( fifo5_dout );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_54_i_i_i_reg_230 );
    sensitive << ( hist_hthr_read_reg_211 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp_fu_194_p2);
    sensitive << ( tmp_57_i_i_i_reg_239 );
    sensitive << ( tmp_58_i_i_i_reg_245 );

    SC_METHOD(thread_tmp_i_i_i_fu_147_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( yi_i_i_i_reg_125 );

    SC_METHOD(thread_xi_fu_165_p2);
    sensitive << ( xi_i_i_i_reg_136 );

    SC_METHOD(thread_yi_fu_153_p2);
    sensitive << ( yi_i_i_i_reg_125 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( hist_hthr_empty_n );
    sensitive << ( hist_lthr_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_i_i_i_fu_147_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_54_i_i_i_fu_159_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "HystThreshold_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, hist_hthr_dout, "(port)hist_hthr_dout");
    sc_trace(mVcdFile, hist_hthr_empty_n, "(port)hist_hthr_empty_n");
    sc_trace(mVcdFile, hist_hthr_read, "(port)hist_hthr_read");
    sc_trace(mVcdFile, hist_lthr_dout, "(port)hist_lthr_dout");
    sc_trace(mVcdFile, hist_lthr_empty_n, "(port)hist_lthr_empty_n");
    sc_trace(mVcdFile, hist_lthr_read, "(port)hist_lthr_read");
    sc_trace(mVcdFile, fifo5_dout, "(port)fifo5_dout");
    sc_trace(mVcdFile, fifo5_empty_n, "(port)fifo5_empty_n");
    sc_trace(mVcdFile, fifo5_read, "(port)fifo5_read");
    sc_trace(mVcdFile, fifo6_din, "(port)fifo6_din");
    sc_trace(mVcdFile, fifo6_full_n, "(port)fifo6_full_n");
    sc_trace(mVcdFile, fifo6_write, "(port)fifo6_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, hist_hthr_blk_n, "hist_hthr_blk_n");
    sc_trace(mVcdFile, hist_lthr_blk_n, "hist_lthr_blk_n");
    sc_trace(mVcdFile, fifo5_blk_n, "fifo5_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_54_i_i_i_reg_230, "tmp_54_i_i_i_reg_230");
    sc_trace(mVcdFile, fifo6_blk_n, "fifo6_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, tmp_54_i_i_i_reg_230_pp0_iter1_reg, "tmp_54_i_i_i_reg_230_pp0_iter1_reg");
    sc_trace(mVcdFile, xi_i_i_i_reg_136, "xi_i_i_i_reg_136");
    sc_trace(mVcdFile, hist_hthr_read_reg_211, "hist_hthr_read_reg_211");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, hist_lthr_read_reg_216, "hist_lthr_read_reg_216");
    sc_trace(mVcdFile, tmp_i_i_i_fu_147_p2, "tmp_i_i_i_fu_147_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, yi_fu_153_p2, "yi_fu_153_p2");
    sc_trace(mVcdFile, yi_reg_225, "yi_reg_225");
    sc_trace(mVcdFile, tmp_54_i_i_i_fu_159_p2, "tmp_54_i_i_i_fu_159_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, xi_fu_165_p2, "xi_fu_165_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_57_i_i_i_fu_171_p2, "tmp_57_i_i_i_fu_171_p2");
    sc_trace(mVcdFile, tmp_57_i_i_i_reg_239, "tmp_57_i_i_i_reg_239");
    sc_trace(mVcdFile, tmp_58_i_i_i_fu_176_p2, "tmp_58_i_i_i_fu_176_p2");
    sc_trace(mVcdFile, tmp_58_i_i_i_reg_245, "tmp_58_i_i_i_reg_245");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, yi_i_i_i_reg_125, "yi_i_i_i_reg_125");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, not_tmp_57_i_i_i_fu_181_p2, "not_tmp_57_i_i_i_fu_181_p2");
    sc_trace(mVcdFile, tmp_fu_194_p2, "tmp_fu_194_p2");
    sc_trace(mVcdFile, pix_hyst_i_i_i_cast_fu_186_p3, "pix_hyst_i_i_i_cast_fu_186_p3");
    sc_trace(mVcdFile, pix_hyst_1_i_i_i_fu_198_p3, "pix_hyst_1_i_i_i_fu_198_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

HystThreshold::~HystThreshold() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void HystThreshold::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(tmp_i_i_i_fu_147_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_i_i_fu_147_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_i_i_fu_147_p2.read()))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_i_i_fu_147_p2.read()))) {
        xi_i_i_i_reg_136 = ap_const_lv10_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_54_i_i_i_fu_159_p2.read()))) {
        xi_i_i_i_reg_136 = xi_fu_165_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        yi_i_i_i_reg_125 = yi_reg_225.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, hist_hthr_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, hist_lthr_empty_n.read())))) {
        yi_i_i_i_reg_125 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, hist_hthr_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, hist_lthr_empty_n.read())))) {
        hist_hthr_read_reg_211 = hist_hthr_dout.read();
        hist_lthr_read_reg_216 = hist_lthr_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_54_i_i_i_reg_230 = tmp_54_i_i_i_fu_159_p2.read();
        tmp_54_i_i_i_reg_230_pp0_iter1_reg = tmp_54_i_i_i_reg_230.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(tmp_54_i_i_i_reg_230.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_57_i_i_i_reg_239 = tmp_57_i_i_i_fu_171_p2.read();
        tmp_58_i_i_i_reg_245 = tmp_58_i_i_i_fu_176_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        yi_reg_225 = yi_fu_153_p2.read();
    }
}

void HystThreshold::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void HystThreshold::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void HystThreshold::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void HystThreshold::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[3];
}

void HystThreshold::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void HystThreshold::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(tmp_54_i_i_i_reg_230.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo5_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_54_i_i_i_reg_230_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo6_full_n.read())));
}

void HystThreshold::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(tmp_54_i_i_i_reg_230.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo5_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_54_i_i_i_reg_230_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo6_full_n.read())));
}

void HystThreshold::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(tmp_54_i_i_i_reg_230.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo5_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_54_i_i_i_reg_230_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo6_full_n.read())));
}

void HystThreshold::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, hist_hthr_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, hist_lthr_empty_n.read()));
}

void HystThreshold::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void HystThreshold::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(tmp_54_i_i_i_reg_230.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, fifo5_empty_n.read()));
}

void HystThreshold::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_54_i_i_i_reg_230_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, fifo6_full_n.read()));
}

void HystThreshold::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(tmp_54_i_i_i_fu_159_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void HystThreshold::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_i_i_i_fu_147_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void HystThreshold::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void HystThreshold::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void HystThreshold::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void HystThreshold::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void HystThreshold::thread_fifo5_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_54_i_i_i_reg_230.read(), ap_const_lv1_0))) {
        fifo5_blk_n = fifo5_empty_n.read();
    } else {
        fifo5_blk_n = ap_const_logic_1;
    }
}

void HystThreshold::thread_fifo5_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_54_i_i_i_reg_230.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        fifo5_read = ap_const_logic_1;
    } else {
        fifo5_read = ap_const_logic_0;
    }
}

void HystThreshold::thread_fifo6_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_54_i_i_i_reg_230_pp0_iter1_reg.read()))) {
        fifo6_blk_n = fifo6_full_n.read();
    } else {
        fifo6_blk_n = ap_const_logic_1;
    }
}

void HystThreshold::thread_fifo6_din() {
    fifo6_din = esl_sext<8,2>(pix_hyst_1_i_i_i_fu_198_p3.read());
}

void HystThreshold::thread_fifo6_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_54_i_i_i_reg_230_pp0_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        fifo6_write = ap_const_logic_1;
    } else {
        fifo6_write = ap_const_logic_0;
    }
}

void HystThreshold::thread_hist_hthr_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        hist_hthr_blk_n = hist_hthr_empty_n.read();
    } else {
        hist_hthr_blk_n = ap_const_logic_1;
    }
}

void HystThreshold::thread_hist_hthr_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, hist_hthr_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, hist_lthr_empty_n.read())))) {
        hist_hthr_read = ap_const_logic_1;
    } else {
        hist_hthr_read = ap_const_logic_0;
    }
}

void HystThreshold::thread_hist_lthr_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        hist_lthr_blk_n = hist_lthr_empty_n.read();
    } else {
        hist_lthr_blk_n = ap_const_logic_1;
    }
}

void HystThreshold::thread_hist_lthr_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, hist_hthr_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, hist_lthr_empty_n.read())))) {
        hist_lthr_read = ap_const_logic_1;
    } else {
        hist_lthr_read = ap_const_logic_0;
    }
}

void HystThreshold::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_i_i_i_fu_147_p2.read(), ap_const_lv1_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void HystThreshold::thread_not_tmp_57_i_i_i_fu_181_p2() {
    not_tmp_57_i_i_i_fu_181_p2 = (tmp_57_i_i_i_reg_239.read() ^ ap_const_lv1_1);
}

void HystThreshold::thread_pix_hyst_1_i_i_i_fu_198_p3() {
    pix_hyst_1_i_i_i_fu_198_p3 = (!tmp_fu_194_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_fu_194_p2.read()[0].to_bool())? pix_hyst_i_i_i_cast_fu_186_p3.read(): ap_const_lv2_1);
}

void HystThreshold::thread_pix_hyst_i_i_i_cast_fu_186_p3() {
    pix_hyst_i_i_i_cast_fu_186_p3 = (!not_tmp_57_i_i_i_fu_181_p2.read()[0].is_01())? sc_lv<2>(): ((not_tmp_57_i_i_i_fu_181_p2.read()[0].to_bool())? ap_const_lv2_3: ap_const_lv2_0);
}

void HystThreshold::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void HystThreshold::thread_start_out() {
    start_out = real_start.read();
}

void HystThreshold::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void HystThreshold::thread_tmp_54_i_i_i_fu_159_p2() {
    tmp_54_i_i_i_fu_159_p2 = (!xi_i_i_i_reg_136.read().is_01() || !ap_const_lv10_200.is_01())? sc_lv<1>(): sc_lv<1>(xi_i_i_i_reg_136.read() == ap_const_lv10_200);
}

void HystThreshold::thread_tmp_57_i_i_i_fu_171_p2() {
    tmp_57_i_i_i_fu_171_p2 = (!fifo5_dout.read().is_01() || !hist_lthr_read_reg_216.read().is_01())? sc_lv<1>(): (sc_biguint<8>(fifo5_dout.read()) < sc_biguint<8>(hist_lthr_read_reg_216.read()));
}

void HystThreshold::thread_tmp_58_i_i_i_fu_176_p2() {
    tmp_58_i_i_i_fu_176_p2 = (!fifo5_dout.read().is_01() || !hist_hthr_read_reg_211.read().is_01())? sc_lv<1>(): (sc_biguint<8>(fifo5_dout.read()) > sc_biguint<8>(hist_hthr_read_reg_211.read()));
}

void HystThreshold::thread_tmp_fu_194_p2() {
    tmp_fu_194_p2 = (tmp_57_i_i_i_reg_239.read() | tmp_58_i_i_i_reg_245.read());
}

void HystThreshold::thread_tmp_i_i_i_fu_147_p2() {
    tmp_i_i_i_fu_147_p2 = (!yi_i_i_i_reg_125.read().is_01() || !ap_const_lv10_200.is_01())? sc_lv<1>(): sc_lv<1>(yi_i_i_i_reg_125.read() == ap_const_lv10_200);
}

void HystThreshold::thread_xi_fu_165_p2() {
    xi_fu_165_p2 = (!xi_i_i_i_reg_136.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(xi_i_i_i_reg_136.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void HystThreshold::thread_yi_fu_153_p2() {
    yi_fu_153_p2 = (!yi_i_i_i_reg_125.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(yi_i_i_i_reg_125.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void HystThreshold::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, hist_hthr_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, hist_lthr_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_i_i_i_fu_147_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_54_i_i_i_fu_159_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(tmp_54_i_i_i_fu_159_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

