// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "NonMaxSuppression.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic NonMaxSuppression::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic NonMaxSuppression::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> NonMaxSuppression::ap_ST_fsm_state1 = "1";
const sc_lv<4> NonMaxSuppression::ap_ST_fsm_state2 = "10";
const sc_lv<4> NonMaxSuppression::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> NonMaxSuppression::ap_ST_fsm_state6 = "1000";
const bool NonMaxSuppression::ap_const_boolean_1 = true;
const sc_lv<32> NonMaxSuppression::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> NonMaxSuppression::ap_const_lv32_2 = "10";
const bool NonMaxSuppression::ap_const_boolean_0 = false;
const sc_lv<1> NonMaxSuppression::ap_const_lv1_0 = "0";
const sc_lv<32> NonMaxSuppression::ap_const_lv32_1 = "1";
const sc_lv<1> NonMaxSuppression::ap_const_lv1_1 = "1";
const sc_lv<10> NonMaxSuppression::ap_const_lv10_0 = "0000000000";
const sc_lv<32> NonMaxSuppression::ap_const_lv32_3 = "11";
const sc_lv<10> NonMaxSuppression::ap_const_lv10_200 = "1000000000";
const sc_lv<10> NonMaxSuppression::ap_const_lv10_1 = "1";
const sc_lv<32> NonMaxSuppression::ap_const_lv32_9 = "1001";
const sc_lv<8> NonMaxSuppression::ap_const_lv8_0 = "00000000";
const sc_lv<10> NonMaxSuppression::ap_const_lv10_1FD = "111111101";
const sc_lv<32> NonMaxSuppression::ap_const_lv32_8 = "1000";
const sc_lv<32> NonMaxSuppression::ap_const_lv32_F = "1111";
const sc_lv<32> NonMaxSuppression::ap_const_lv32_10 = "10000";
const sc_lv<32> NonMaxSuppression::ap_const_lv32_17 = "10111";
const sc_lv<32> NonMaxSuppression::ap_const_lv32_4 = "100";
const sc_lv<32> NonMaxSuppression::ap_const_lv32_5 = "101";
const sc_lv<2> NonMaxSuppression::ap_const_lv2_0 = "00";
const sc_lv<2> NonMaxSuppression::ap_const_lv2_1 = "1";
const sc_lv<2> NonMaxSuppression::ap_const_lv2_2 = "10";
const sc_lv<2> NonMaxSuppression::ap_const_lv2_3 = "11";

NonMaxSuppression::NonMaxSuppression(sc_module_name name) : sc_module(name), mVcdFile(0) {
    line_buf_value_U = new Sobel_512u_512u_sfYi("line_buf_value_U");
    line_buf_value_U->clk(ap_clk);
    line_buf_value_U->reset(ap_rst);
    line_buf_value_U->address0(line_buf_value_address0);
    line_buf_value_U->ce0(line_buf_value_ce0);
    line_buf_value_U->q0(line_buf_value_q0);
    line_buf_value_U->address1(line_buf_value_addr_reg_712);
    line_buf_value_U->ce1(line_buf_value_ce1);
    line_buf_value_U->we1(line_buf_value_we1);
    line_buf_value_U->d1(line_buf_value_d1);
    line_buf_grad_U = new NonMaxSuppressionmb6("line_buf_grad_U");
    line_buf_grad_U->clk(ap_clk);
    line_buf_grad_U->reset(ap_rst);
    line_buf_grad_U->address0(line_buf_grad_address0);
    line_buf_grad_U->ce0(line_buf_grad_ce0);
    line_buf_grad_U->q0(line_buf_grad_q0);
    line_buf_grad_U->address1(line_buf_grad_addr_reg_718);
    line_buf_grad_U->ce1(line_buf_grad_ce1);
    line_buf_grad_U->we1(line_buf_grad_we1);
    line_buf_grad_U->d1(line_buf_grad_d1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( fifo3_value_empty_n );
    sensitive << ( fifo3_grad_empty_n );
    sensitive << ( fifo4_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_31_i_reg_703_pp0_iter1_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( fifo3_value_empty_n );
    sensitive << ( fifo3_grad_empty_n );
    sensitive << ( fifo4_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_31_i_reg_703_pp0_iter1_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( fifo3_value_empty_n );
    sensitive << ( fifo3_grad_empty_n );
    sensitive << ( fifo4_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_31_i_reg_703_pp0_iter1_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( fifo3_value_empty_n );
    sensitive << ( fifo3_grad_empty_n );
    sensitive << ( tmp_31_i_reg_703 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);
    sensitive << ( fifo4_full_n );
    sensitive << ( tmp_31_i_reg_703_pp0_iter1_reg );

    SC_METHOD(thread_ap_condition_pp0_exit_iter1_state4);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( tmp_i_fu_233_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_fifo3_grad_blk_n);
    sensitive << ( fifo3_grad_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_31_i_reg_703 );

    SC_METHOD(thread_fifo3_grad_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_fifo3_value_blk_n);
    sensitive << ( fifo3_value_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_31_i_reg_703 );

    SC_METHOD(thread_fifo3_value_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_fifo4_blk_n);
    sensitive << ( fifo4_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_31_i_reg_703_pp0_iter1_reg );

    SC_METHOD(thread_fifo4_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_31_i_reg_703_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( or_cond5_i_fu_633_p2 );
    sensitive << ( value_nms_7_i_fu_622_p3 );

    SC_METHOD(thread_fifo4_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_31_i_reg_703_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_icmp3_fu_301_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_31_i_fu_273_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_13_fu_291_p4 );

    SC_METHOD(thread_icmp_fu_255_p2);
    sensitive << ( tmp_i_fu_233_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_12_fu_245_p4 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( tmp_i_fu_233_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_line_buf_grad_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_32_i_fu_285_p1 );

    SC_METHOD(thread_line_buf_grad_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_line_buf_grad_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_line_buf_grad_d1);
    sensitive << ( fifo3_grad_dout );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_23_i_fu_383_p4 );

    SC_METHOD(thread_line_buf_grad_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_line_buf_value_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_32_i_fu_285_p1 );

    SC_METHOD(thread_line_buf_value_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_line_buf_value_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_line_buf_value_d1);
    sensitive << ( fifo3_value_dout );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_21_i_fu_364_p4 );

    SC_METHOD(thread_line_buf_value_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_or_cond1_fu_583_p2);
    sensitive << ( tmp_39_i_reg_750 );
    sensitive << ( tmp_41_i_reg_755 );

    SC_METHOD(thread_or_cond1_i_fu_470_p2);
    sensitive << ( tmp_42_i_fu_458_p2 );
    sensitive << ( tmp_43_i_fu_464_p2 );

    SC_METHOD(thread_or_cond2_fu_594_p2);
    sensitive << ( tmp_42_i_reg_760 );
    sensitive << ( tmp_45_i_reg_765 );

    SC_METHOD(thread_or_cond5_i_fu_633_p2);
    sensitive << ( tmp1_reg_698 );
    sensitive << ( tmp_fu_629_p2 );

    SC_METHOD(thread_or_cond_fu_420_p2);
    sensitive << ( tmp_36_i_fu_408_p2 );
    sensitive << ( tmp_38_i_fu_414_p2 );

    SC_METHOD(thread_p_window_buf_1_1_va_1_fu_587_p3);
    sensitive << ( window_buf_1_1_val_reg_734 );
    sensitive << ( or_cond1_fu_583_p2 );

    SC_METHOD(thread_p_window_buf_1_1_va_2_fu_598_p3);
    sensitive << ( window_buf_1_1_val_reg_734 );
    sensitive << ( or_cond2_fu_594_p2 );

    SC_METHOD(thread_p_window_buf_1_1_va_fu_426_p3);
    sensitive << ( value_nms_1_fu_136 );
    sensitive << ( or_cond_fu_420_p2 );

    SC_METHOD(thread_p_window_buf_value_lo_fu_476_p3);
    sensitive << ( value_nms_1_fu_136 );
    sensitive << ( or_cond1_i_fu_470_p2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_sel_tmp13_demorgan_fu_530_p2);
    sensitive << ( sel_tmp2_demorgan_fu_496_p2 );
    sensitive << ( tmp_40_i_fu_452_p2 );

    SC_METHOD(thread_sel_tmp1_fu_542_p2);
    sensitive << ( tmp_44_i_fu_484_p2 );
    sensitive << ( sel_tmp_fu_536_p2 );

    SC_METHOD(thread_sel_tmp2_demorgan_fu_496_p2);
    sensitive << ( tmp_35_i_fu_402_p2 );
    sensitive << ( tmp_37_i_fu_434_p2 );

    SC_METHOD(thread_sel_tmp2_fu_502_p2);
    sensitive << ( sel_tmp2_demorgan_fu_496_p2 );

    SC_METHOD(thread_sel_tmp3_fu_508_p2);
    sensitive << ( tmp_40_i_fu_452_p2 );
    sensitive << ( sel_tmp2_fu_502_p2 );

    SC_METHOD(thread_sel_tmp4_fu_514_p3);
    sensitive << ( value_nms_1_fu_136 );
    sensitive << ( sel_tmp3_fu_508_p2 );
    sensitive << ( p_window_buf_value_lo_fu_476_p3 );

    SC_METHOD(thread_sel_tmp5_fu_522_p3);
    sensitive << ( tmp_35_i_fu_402_p2 );
    sensitive << ( p_window_buf_1_1_va_fu_426_p3 );
    sensitive << ( sel_tmp4_fu_514_p3 );

    SC_METHOD(thread_sel_tmp6_fu_605_p2);
    sensitive << ( tmp_35_i_reg_740 );

    SC_METHOD(thread_sel_tmp7_fu_610_p2);
    sensitive << ( tmp_37_i_reg_745 );
    sensitive << ( sel_tmp6_fu_605_p2 );

    SC_METHOD(thread_sel_tmp8_fu_615_p3);
    sensitive << ( sel_tmp5_reg_770 );
    sensitive << ( sel_tmp7_fu_610_p2 );
    sensitive << ( p_window_buf_1_1_va_1_fu_587_p3 );

    SC_METHOD(thread_sel_tmp_fu_536_p2);
    sensitive << ( sel_tmp13_demorgan_fu_530_p2 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp1_fu_267_p2);
    sensitive << ( icmp_fu_255_p2 );
    sensitive << ( tmp_30_i_fu_261_p2 );

    SC_METHOD(thread_tmp_12_fu_245_p4);
    sensitive << ( yi_i_reg_211 );

    SC_METHOD(thread_tmp_13_fu_291_p4);
    sensitive << ( xi_i_reg_222 );

    SC_METHOD(thread_tmp_21_i_fu_364_p4);
    sensitive << ( line_buf_value_q0 );

    SC_METHOD(thread_tmp_23_i_fu_383_p4);
    sensitive << ( line_buf_grad_q0 );

    SC_METHOD(thread_tmp_30_i_fu_261_p2);
    sensitive << ( tmp_i_fu_233_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( yi_i_reg_211 );

    SC_METHOD(thread_tmp_31_i_fu_273_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( xi_i_reg_222 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_32_i_fu_285_p1);
    sensitive << ( xi_i_reg_222 );

    SC_METHOD(thread_tmp_35_i_fu_402_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grad_nms_fu_148 );

    SC_METHOD(thread_tmp_36_i_fu_408_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( value_nms_fu_132 );
    sensitive << ( value_nms_1_fu_136 );

    SC_METHOD(thread_tmp_37_i_fu_434_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grad_nms_fu_148 );

    SC_METHOD(thread_tmp_38_i_fu_414_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( value_nms_1_fu_136 );
    sensitive << ( window_buf_1_2_val_fu_344_p4 );

    SC_METHOD(thread_tmp_39_i_fu_440_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( window_buf_0_1_val_fu_124 );
    sensitive << ( value_nms_1_fu_136 );

    SC_METHOD(thread_tmp_40_i_fu_452_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grad_nms_fu_148 );

    SC_METHOD(thread_tmp_41_i_fu_446_p2);
    sensitive << ( fifo3_value_dout );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( value_nms_1_fu_136 );

    SC_METHOD(thread_tmp_42_i_fu_458_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( window_buf_0_2_val_fu_334_p4 );
    sensitive << ( value_nms_1_fu_136 );

    SC_METHOD(thread_tmp_43_i_fu_464_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( value_nms_1_fu_136 );
    sensitive << ( window_buf_2_1_val_1_fu_144 );

    SC_METHOD(thread_tmp_44_i_fu_484_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grad_nms_fu_148 );

    SC_METHOD(thread_tmp_45_i_fu_490_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_31_i_reg_703 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( value_nms_1_fu_136 );
    sensitive << ( window_buf_2_1_val_fu_140 );

    SC_METHOD(thread_tmp_48_i_fu_307_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( xi_i_reg_222 );
    sensitive << ( tmp_31_i_fu_273_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_fu_629_p2);
    sensitive << ( icmp3_reg_724_pp0_iter1_reg );
    sensitive << ( tmp_48_i_reg_729_pp0_iter1_reg );

    SC_METHOD(thread_tmp_i_fu_233_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( yi_i_reg_211 );

    SC_METHOD(thread_value_nms_7_i_fu_622_p3);
    sensitive << ( sel_tmp1_reg_775 );
    sensitive << ( p_window_buf_1_1_va_2_fu_598_p3 );
    sensitive << ( sel_tmp8_fu_615_p3 );

    SC_METHOD(thread_window_buf_0_2_val_fu_334_p4);
    sensitive << ( line_buf_value_q0 );

    SC_METHOD(thread_window_buf_1_2_val_fu_344_p4);
    sensitive << ( line_buf_value_q0 );

    SC_METHOD(thread_xi_fu_279_p2);
    sensitive << ( xi_i_reg_222 );

    SC_METHOD(thread_yi_fu_239_p2);
    sensitive << ( yi_i_reg_211 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_i_fu_233_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "NonMaxSuppression_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, fifo3_value_dout, "(port)fifo3_value_dout");
    sc_trace(mVcdFile, fifo3_value_empty_n, "(port)fifo3_value_empty_n");
    sc_trace(mVcdFile, fifo3_value_read, "(port)fifo3_value_read");
    sc_trace(mVcdFile, fifo3_grad_dout, "(port)fifo3_grad_dout");
    sc_trace(mVcdFile, fifo3_grad_empty_n, "(port)fifo3_grad_empty_n");
    sc_trace(mVcdFile, fifo3_grad_read, "(port)fifo3_grad_read");
    sc_trace(mVcdFile, fifo4_din, "(port)fifo4_din");
    sc_trace(mVcdFile, fifo4_full_n, "(port)fifo4_full_n");
    sc_trace(mVcdFile, fifo4_write, "(port)fifo4_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, fifo3_value_blk_n, "fifo3_value_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_31_i_reg_703, "tmp_31_i_reg_703");
    sc_trace(mVcdFile, fifo3_grad_blk_n, "fifo3_grad_blk_n");
    sc_trace(mVcdFile, fifo4_blk_n, "fifo4_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, tmp_31_i_reg_703_pp0_iter1_reg, "tmp_31_i_reg_703_pp0_iter1_reg");
    sc_trace(mVcdFile, xi_i_reg_222, "xi_i_reg_222");
    sc_trace(mVcdFile, tmp_i_fu_233_p2, "tmp_i_fu_233_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, yi_fu_239_p2, "yi_fu_239_p2");
    sc_trace(mVcdFile, yi_reg_693, "yi_reg_693");
    sc_trace(mVcdFile, tmp1_fu_267_p2, "tmp1_fu_267_p2");
    sc_trace(mVcdFile, tmp1_reg_698, "tmp1_reg_698");
    sc_trace(mVcdFile, tmp_31_i_fu_273_p2, "tmp_31_i_fu_273_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, xi_fu_279_p2, "xi_fu_279_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, line_buf_value_addr_reg_712, "line_buf_value_addr_reg_712");
    sc_trace(mVcdFile, line_buf_grad_addr_reg_718, "line_buf_grad_addr_reg_718");
    sc_trace(mVcdFile, icmp3_fu_301_p2, "icmp3_fu_301_p2");
    sc_trace(mVcdFile, icmp3_reg_724, "icmp3_reg_724");
    sc_trace(mVcdFile, icmp3_reg_724_pp0_iter1_reg, "icmp3_reg_724_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_48_i_fu_307_p2, "tmp_48_i_fu_307_p2");
    sc_trace(mVcdFile, tmp_48_i_reg_729, "tmp_48_i_reg_729");
    sc_trace(mVcdFile, tmp_48_i_reg_729_pp0_iter1_reg, "tmp_48_i_reg_729_pp0_iter1_reg");
    sc_trace(mVcdFile, window_buf_1_1_val_reg_734, "window_buf_1_1_val_reg_734");
    sc_trace(mVcdFile, tmp_35_i_fu_402_p2, "tmp_35_i_fu_402_p2");
    sc_trace(mVcdFile, tmp_35_i_reg_740, "tmp_35_i_reg_740");
    sc_trace(mVcdFile, tmp_37_i_fu_434_p2, "tmp_37_i_fu_434_p2");
    sc_trace(mVcdFile, tmp_37_i_reg_745, "tmp_37_i_reg_745");
    sc_trace(mVcdFile, tmp_39_i_fu_440_p2, "tmp_39_i_fu_440_p2");
    sc_trace(mVcdFile, tmp_39_i_reg_750, "tmp_39_i_reg_750");
    sc_trace(mVcdFile, tmp_41_i_fu_446_p2, "tmp_41_i_fu_446_p2");
    sc_trace(mVcdFile, tmp_41_i_reg_755, "tmp_41_i_reg_755");
    sc_trace(mVcdFile, tmp_42_i_fu_458_p2, "tmp_42_i_fu_458_p2");
    sc_trace(mVcdFile, tmp_42_i_reg_760, "tmp_42_i_reg_760");
    sc_trace(mVcdFile, tmp_45_i_fu_490_p2, "tmp_45_i_fu_490_p2");
    sc_trace(mVcdFile, tmp_45_i_reg_765, "tmp_45_i_reg_765");
    sc_trace(mVcdFile, sel_tmp5_fu_522_p3, "sel_tmp5_fu_522_p3");
    sc_trace(mVcdFile, sel_tmp5_reg_770, "sel_tmp5_reg_770");
    sc_trace(mVcdFile, sel_tmp1_fu_542_p2, "sel_tmp1_fu_542_p2");
    sc_trace(mVcdFile, sel_tmp1_reg_775, "sel_tmp1_reg_775");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter1_state4, "ap_condition_pp0_exit_iter1_state4");
    sc_trace(mVcdFile, line_buf_value_address0, "line_buf_value_address0");
    sc_trace(mVcdFile, line_buf_value_ce0, "line_buf_value_ce0");
    sc_trace(mVcdFile, line_buf_value_q0, "line_buf_value_q0");
    sc_trace(mVcdFile, line_buf_value_ce1, "line_buf_value_ce1");
    sc_trace(mVcdFile, line_buf_value_we1, "line_buf_value_we1");
    sc_trace(mVcdFile, line_buf_value_d1, "line_buf_value_d1");
    sc_trace(mVcdFile, line_buf_grad_address0, "line_buf_grad_address0");
    sc_trace(mVcdFile, line_buf_grad_ce0, "line_buf_grad_ce0");
    sc_trace(mVcdFile, line_buf_grad_q0, "line_buf_grad_q0");
    sc_trace(mVcdFile, line_buf_grad_ce1, "line_buf_grad_ce1");
    sc_trace(mVcdFile, line_buf_grad_we1, "line_buf_grad_we1");
    sc_trace(mVcdFile, line_buf_grad_d1, "line_buf_grad_d1");
    sc_trace(mVcdFile, yi_i_reg_211, "yi_i_reg_211");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_32_i_fu_285_p1, "tmp_32_i_fu_285_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, window_buf_0_1_val_fu_124, "window_buf_0_1_val_fu_124");
    sc_trace(mVcdFile, window_buf_0_1_val_1_fu_128, "window_buf_0_1_val_1_fu_128");
    sc_trace(mVcdFile, window_buf_0_2_val_fu_334_p4, "window_buf_0_2_val_fu_334_p4");
    sc_trace(mVcdFile, value_nms_fu_132, "value_nms_fu_132");
    sc_trace(mVcdFile, value_nms_1_fu_136, "value_nms_1_fu_136");
    sc_trace(mVcdFile, window_buf_1_2_val_fu_344_p4, "window_buf_1_2_val_fu_344_p4");
    sc_trace(mVcdFile, window_buf_2_1_val_fu_140, "window_buf_2_1_val_fu_140");
    sc_trace(mVcdFile, window_buf_2_1_val_1_fu_144, "window_buf_2_1_val_1_fu_144");
    sc_trace(mVcdFile, grad_nms_fu_148, "grad_nms_fu_148");
    sc_trace(mVcdFile, tmp_12_fu_245_p4, "tmp_12_fu_245_p4");
    sc_trace(mVcdFile, icmp_fu_255_p2, "icmp_fu_255_p2");
    sc_trace(mVcdFile, tmp_30_i_fu_261_p2, "tmp_30_i_fu_261_p2");
    sc_trace(mVcdFile, tmp_13_fu_291_p4, "tmp_13_fu_291_p4");
    sc_trace(mVcdFile, tmp_21_i_fu_364_p4, "tmp_21_i_fu_364_p4");
    sc_trace(mVcdFile, tmp_23_i_fu_383_p4, "tmp_23_i_fu_383_p4");
    sc_trace(mVcdFile, tmp_36_i_fu_408_p2, "tmp_36_i_fu_408_p2");
    sc_trace(mVcdFile, tmp_38_i_fu_414_p2, "tmp_38_i_fu_414_p2");
    sc_trace(mVcdFile, or_cond_fu_420_p2, "or_cond_fu_420_p2");
    sc_trace(mVcdFile, tmp_43_i_fu_464_p2, "tmp_43_i_fu_464_p2");
    sc_trace(mVcdFile, or_cond1_i_fu_470_p2, "or_cond1_i_fu_470_p2");
    sc_trace(mVcdFile, sel_tmp2_demorgan_fu_496_p2, "sel_tmp2_demorgan_fu_496_p2");
    sc_trace(mVcdFile, tmp_40_i_fu_452_p2, "tmp_40_i_fu_452_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_502_p2, "sel_tmp2_fu_502_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_508_p2, "sel_tmp3_fu_508_p2");
    sc_trace(mVcdFile, p_window_buf_value_lo_fu_476_p3, "p_window_buf_value_lo_fu_476_p3");
    sc_trace(mVcdFile, p_window_buf_1_1_va_fu_426_p3, "p_window_buf_1_1_va_fu_426_p3");
    sc_trace(mVcdFile, sel_tmp4_fu_514_p3, "sel_tmp4_fu_514_p3");
    sc_trace(mVcdFile, sel_tmp13_demorgan_fu_530_p2, "sel_tmp13_demorgan_fu_530_p2");
    sc_trace(mVcdFile, tmp_44_i_fu_484_p2, "tmp_44_i_fu_484_p2");
    sc_trace(mVcdFile, sel_tmp_fu_536_p2, "sel_tmp_fu_536_p2");
    sc_trace(mVcdFile, or_cond1_fu_583_p2, "or_cond1_fu_583_p2");
    sc_trace(mVcdFile, or_cond2_fu_594_p2, "or_cond2_fu_594_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_605_p2, "sel_tmp6_fu_605_p2");
    sc_trace(mVcdFile, sel_tmp7_fu_610_p2, "sel_tmp7_fu_610_p2");
    sc_trace(mVcdFile, p_window_buf_1_1_va_1_fu_587_p3, "p_window_buf_1_1_va_1_fu_587_p3");
    sc_trace(mVcdFile, p_window_buf_1_1_va_2_fu_598_p3, "p_window_buf_1_1_va_2_fu_598_p3");
    sc_trace(mVcdFile, sel_tmp8_fu_615_p3, "sel_tmp8_fu_615_p3");
    sc_trace(mVcdFile, tmp_fu_629_p2, "tmp_fu_629_p2");
    sc_trace(mVcdFile, or_cond5_i_fu_633_p2, "or_cond5_i_fu_633_p2");
    sc_trace(mVcdFile, value_nms_7_i_fu_622_p3, "value_nms_7_i_fu_622_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

NonMaxSuppression::~NonMaxSuppression() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete line_buf_value_U;
    delete line_buf_grad_U;
}

void NonMaxSuppression::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(tmp_i_fu_233_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(tmp_31_i_fu_273_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_233_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_233_p2.read())) || 
                    (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter1_state4.read())))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter1_state4.read()))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_233_p2.read()))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_i_fu_273_p2.read()))) {
        xi_i_reg_222 = xi_fu_279_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_233_p2.read()))) {
        xi_i_reg_222 = ap_const_lv10_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        yi_i_reg_211 = yi_reg_693.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        yi_i_reg_211 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grad_nms_fu_148 = line_buf_grad_q0.read().range(5, 4);
        value_nms_1_fu_136 = line_buf_value_q0.read().range(23, 16);
        value_nms_fu_132 = value_nms_1_fu_136.read();
        window_buf_0_1_val_1_fu_128 = line_buf_value_q0.read().range(15, 8);
        window_buf_0_1_val_fu_124 = window_buf_0_1_val_1_fu_128.read();
        window_buf_2_1_val_1_fu_144 = fifo3_value_dout.read();
        window_buf_2_1_val_fu_140 = window_buf_2_1_val_1_fu_144.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_i_fu_273_p2.read()))) {
        icmp3_reg_724 = icmp3_fu_301_p2.read();
        line_buf_grad_addr_reg_718 =  (sc_lv<9>) (tmp_32_i_fu_285_p1.read());
        line_buf_value_addr_reg_712 =  (sc_lv<9>) (tmp_32_i_fu_285_p1.read());
        tmp_48_i_reg_729 = tmp_48_i_fu_307_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp3_reg_724_pp0_iter1_reg = icmp3_reg_724.read();
        tmp_31_i_reg_703 = tmp_31_i_fu_273_p2.read();
        tmp_31_i_reg_703_pp0_iter1_reg = tmp_31_i_reg_703.read();
        tmp_48_i_reg_729_pp0_iter1_reg = tmp_48_i_reg_729.read();
        window_buf_1_1_val_reg_734 = value_nms_1_fu_136.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        sel_tmp1_reg_775 = sel_tmp1_fu_542_p2.read();
        sel_tmp5_reg_770 = sel_tmp5_fu_522_p3.read();
        tmp_35_i_reg_740 = tmp_35_i_fu_402_p2.read();
        tmp_37_i_reg_745 = tmp_37_i_fu_434_p2.read();
        tmp_39_i_reg_750 = tmp_39_i_fu_440_p2.read();
        tmp_41_i_reg_755 = tmp_41_i_fu_446_p2.read();
        tmp_42_i_reg_760 = tmp_42_i_fu_458_p2.read();
        tmp_45_i_reg_765 = tmp_45_i_fu_490_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_233_p2.read()))) {
        tmp1_reg_698 = tmp1_fu_267_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        yi_reg_693 = yi_fu_239_p2.read();
    }
}

void NonMaxSuppression::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void NonMaxSuppression::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void NonMaxSuppression::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void NonMaxSuppression::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[3];
}

void NonMaxSuppression::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void NonMaxSuppression::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo3_value_empty_n.read())) || 
   (esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo3_grad_empty_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_i_reg_703_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo4_full_n.read())));
}

void NonMaxSuppression::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo3_value_empty_n.read())) || 
   (esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo3_grad_empty_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_i_reg_703_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo4_full_n.read())));
}

void NonMaxSuppression::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo3_value_empty_n.read())) || 
   (esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo3_grad_empty_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_i_reg_703_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo4_full_n.read())));
}

void NonMaxSuppression::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void NonMaxSuppression::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void NonMaxSuppression::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = ((esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo3_value_empty_n.read())) || (esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo3_grad_empty_n.read())));
}

void NonMaxSuppression::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_i_reg_703_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, fifo4_full_n.read()));
}

void NonMaxSuppression::thread_ap_condition_pp0_exit_iter1_state4() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
        ap_condition_pp0_exit_iter1_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter1_state4 = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_i_fu_233_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void NonMaxSuppression::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void NonMaxSuppression::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void NonMaxSuppression::thread_fifo3_grad_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0))) {
        fifo3_grad_blk_n = fifo3_grad_empty_n.read();
    } else {
        fifo3_grad_blk_n = ap_const_logic_1;
    }
}

void NonMaxSuppression::thread_fifo3_grad_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        fifo3_grad_read = ap_const_logic_1;
    } else {
        fifo3_grad_read = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_fifo3_value_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0))) {
        fifo3_value_blk_n = fifo3_value_empty_n.read();
    } else {
        fifo3_value_blk_n = ap_const_logic_1;
    }
}

void NonMaxSuppression::thread_fifo3_value_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        fifo3_value_read = ap_const_logic_1;
    } else {
        fifo3_value_read = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_fifo4_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_i_reg_703_pp0_iter1_reg.read()))) {
        fifo4_blk_n = fifo4_full_n.read();
    } else {
        fifo4_blk_n = ap_const_logic_1;
    }
}

void NonMaxSuppression::thread_fifo4_din() {
    fifo4_din = (!or_cond5_i_fu_633_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond5_i_fu_633_p2.read()[0].to_bool())? value_nms_7_i_fu_622_p3.read(): ap_const_lv8_0);
}

void NonMaxSuppression::thread_fifo4_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_i_reg_703_pp0_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        fifo4_write = ap_const_logic_1;
    } else {
        fifo4_write = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_icmp3_fu_301_p2() {
    icmp3_fu_301_p2 = (!tmp_13_fu_291_p4.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_13_fu_291_p4.read() != ap_const_lv8_0);
}

void NonMaxSuppression::thread_icmp_fu_255_p2() {
    icmp_fu_255_p2 = (!tmp_12_fu_245_p4.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_12_fu_245_p4.read() != ap_const_lv8_0);
}

void NonMaxSuppression::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_i_fu_233_p2.read(), ap_const_lv1_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_line_buf_grad_address0() {
    line_buf_grad_address0 =  (sc_lv<9>) (tmp_32_i_fu_285_p1.read());
}

void NonMaxSuppression::thread_line_buf_grad_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        line_buf_grad_ce0 = ap_const_logic_1;
    } else {
        line_buf_grad_ce0 = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_line_buf_grad_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        line_buf_grad_ce1 = ap_const_logic_1;
    } else {
        line_buf_grad_ce1 = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_line_buf_grad_d1() {
    line_buf_grad_d1 = esl_concat<2,4>(fifo3_grad_dout.read(), tmp_23_i_fu_383_p4.read());
}

void NonMaxSuppression::thread_line_buf_grad_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        line_buf_grad_we1 = ap_const_logic_1;
    } else {
        line_buf_grad_we1 = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_line_buf_value_address0() {
    line_buf_value_address0 =  (sc_lv<9>) (tmp_32_i_fu_285_p1.read());
}

void NonMaxSuppression::thread_line_buf_value_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        line_buf_value_ce0 = ap_const_logic_1;
    } else {
        line_buf_value_ce0 = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_line_buf_value_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        line_buf_value_ce1 = ap_const_logic_1;
    } else {
        line_buf_value_ce1 = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_line_buf_value_d1() {
    line_buf_value_d1 = esl_concat<8,16>(fifo3_value_dout.read(), tmp_21_i_fu_364_p4.read());
}

void NonMaxSuppression::thread_line_buf_value_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_31_i_reg_703.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        line_buf_value_we1 = ap_const_logic_1;
    } else {
        line_buf_value_we1 = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_or_cond1_fu_583_p2() {
    or_cond1_fu_583_p2 = (tmp_39_i_reg_750.read() | tmp_41_i_reg_755.read());
}

void NonMaxSuppression::thread_or_cond1_i_fu_470_p2() {
    or_cond1_i_fu_470_p2 = (tmp_42_i_fu_458_p2.read() | tmp_43_i_fu_464_p2.read());
}

void NonMaxSuppression::thread_or_cond2_fu_594_p2() {
    or_cond2_fu_594_p2 = (tmp_45_i_reg_765.read() | tmp_42_i_reg_760.read());
}

void NonMaxSuppression::thread_or_cond5_i_fu_633_p2() {
    or_cond5_i_fu_633_p2 = (tmp1_reg_698.read() & tmp_fu_629_p2.read());
}

void NonMaxSuppression::thread_or_cond_fu_420_p2() {
    or_cond_fu_420_p2 = (tmp_36_i_fu_408_p2.read() | tmp_38_i_fu_414_p2.read());
}

void NonMaxSuppression::thread_p_window_buf_1_1_va_1_fu_587_p3() {
    p_window_buf_1_1_va_1_fu_587_p3 = (!or_cond1_fu_583_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond1_fu_583_p2.read()[0].to_bool())? ap_const_lv8_0: window_buf_1_1_val_reg_734.read());
}

void NonMaxSuppression::thread_p_window_buf_1_1_va_2_fu_598_p3() {
    p_window_buf_1_1_va_2_fu_598_p3 = (!or_cond2_fu_594_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond2_fu_594_p2.read()[0].to_bool())? ap_const_lv8_0: window_buf_1_1_val_reg_734.read());
}

void NonMaxSuppression::thread_p_window_buf_1_1_va_fu_426_p3() {
    p_window_buf_1_1_va_fu_426_p3 = (!or_cond_fu_420_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond_fu_420_p2.read()[0].to_bool())? ap_const_lv8_0: value_nms_1_fu_136.read());
}

void NonMaxSuppression::thread_p_window_buf_value_lo_fu_476_p3() {
    p_window_buf_value_lo_fu_476_p3 = (!or_cond1_i_fu_470_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond1_i_fu_470_p2.read()[0].to_bool())? ap_const_lv8_0: value_nms_1_fu_136.read());
}

void NonMaxSuppression::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void NonMaxSuppression::thread_sel_tmp13_demorgan_fu_530_p2() {
    sel_tmp13_demorgan_fu_530_p2 = (sel_tmp2_demorgan_fu_496_p2.read() | tmp_40_i_fu_452_p2.read());
}

void NonMaxSuppression::thread_sel_tmp1_fu_542_p2() {
    sel_tmp1_fu_542_p2 = (tmp_44_i_fu_484_p2.read() & sel_tmp_fu_536_p2.read());
}

void NonMaxSuppression::thread_sel_tmp2_demorgan_fu_496_p2() {
    sel_tmp2_demorgan_fu_496_p2 = (tmp_35_i_fu_402_p2.read() | tmp_37_i_fu_434_p2.read());
}

void NonMaxSuppression::thread_sel_tmp2_fu_502_p2() {
    sel_tmp2_fu_502_p2 = (sel_tmp2_demorgan_fu_496_p2.read() ^ ap_const_lv1_1);
}

void NonMaxSuppression::thread_sel_tmp3_fu_508_p2() {
    sel_tmp3_fu_508_p2 = (tmp_40_i_fu_452_p2.read() & sel_tmp2_fu_502_p2.read());
}

void NonMaxSuppression::thread_sel_tmp4_fu_514_p3() {
    sel_tmp4_fu_514_p3 = (!sel_tmp3_fu_508_p2.read()[0].is_01())? sc_lv<8>(): ((sel_tmp3_fu_508_p2.read()[0].to_bool())? p_window_buf_value_lo_fu_476_p3.read(): value_nms_1_fu_136.read());
}

void NonMaxSuppression::thread_sel_tmp5_fu_522_p3() {
    sel_tmp5_fu_522_p3 = (!tmp_35_i_fu_402_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_35_i_fu_402_p2.read()[0].to_bool())? p_window_buf_1_1_va_fu_426_p3.read(): sel_tmp4_fu_514_p3.read());
}

void NonMaxSuppression::thread_sel_tmp6_fu_605_p2() {
    sel_tmp6_fu_605_p2 = (tmp_35_i_reg_740.read() ^ ap_const_lv1_1);
}

void NonMaxSuppression::thread_sel_tmp7_fu_610_p2() {
    sel_tmp7_fu_610_p2 = (tmp_37_i_reg_745.read() & sel_tmp6_fu_605_p2.read());
}

void NonMaxSuppression::thread_sel_tmp8_fu_615_p3() {
    sel_tmp8_fu_615_p3 = (!sel_tmp7_fu_610_p2.read()[0].is_01())? sc_lv<8>(): ((sel_tmp7_fu_610_p2.read()[0].to_bool())? p_window_buf_1_1_va_1_fu_587_p3.read(): sel_tmp5_reg_770.read());
}

void NonMaxSuppression::thread_sel_tmp_fu_536_p2() {
    sel_tmp_fu_536_p2 = (sel_tmp13_demorgan_fu_530_p2.read() ^ ap_const_lv1_1);
}

void NonMaxSuppression::thread_start_out() {
    start_out = real_start.read();
}

void NonMaxSuppression::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void NonMaxSuppression::thread_tmp1_fu_267_p2() {
    tmp1_fu_267_p2 = (icmp_fu_255_p2.read() & tmp_30_i_fu_261_p2.read());
}

void NonMaxSuppression::thread_tmp_12_fu_245_p4() {
    tmp_12_fu_245_p4 = yi_i_reg_211.read().range(9, 2);
}

void NonMaxSuppression::thread_tmp_13_fu_291_p4() {
    tmp_13_fu_291_p4 = xi_i_reg_222.read().range(9, 2);
}

void NonMaxSuppression::thread_tmp_21_i_fu_364_p4() {
    tmp_21_i_fu_364_p4 = line_buf_value_q0.read().range(23, 8);
}

void NonMaxSuppression::thread_tmp_23_i_fu_383_p4() {
    tmp_23_i_fu_383_p4 = line_buf_grad_q0.read().range(5, 2);
}

void NonMaxSuppression::thread_tmp_30_i_fu_261_p2() {
    tmp_30_i_fu_261_p2 = (!yi_i_reg_211.read().is_01() || !ap_const_lv10_1FD.is_01())? sc_lv<1>(): (sc_biguint<10>(yi_i_reg_211.read()) < sc_biguint<10>(ap_const_lv10_1FD));
}

void NonMaxSuppression::thread_tmp_31_i_fu_273_p2() {
    tmp_31_i_fu_273_p2 = (!xi_i_reg_222.read().is_01() || !ap_const_lv10_200.is_01())? sc_lv<1>(): sc_lv<1>(xi_i_reg_222.read() == ap_const_lv10_200);
}

void NonMaxSuppression::thread_tmp_32_i_fu_285_p1() {
    tmp_32_i_fu_285_p1 = esl_zext<64,10>(xi_i_reg_222.read());
}

void NonMaxSuppression::thread_tmp_35_i_fu_402_p2() {
    tmp_35_i_fu_402_p2 = (!grad_nms_fu_148.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(grad_nms_fu_148.read() == ap_const_lv2_0);
}

void NonMaxSuppression::thread_tmp_36_i_fu_408_p2() {
    tmp_36_i_fu_408_p2 = (!value_nms_1_fu_136.read().is_01() || !value_nms_fu_132.read().is_01())? sc_lv<1>(): (sc_biguint<8>(value_nms_1_fu_136.read()) < sc_biguint<8>(value_nms_fu_132.read()));
}

void NonMaxSuppression::thread_tmp_37_i_fu_434_p2() {
    tmp_37_i_fu_434_p2 = (!grad_nms_fu_148.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(grad_nms_fu_148.read() == ap_const_lv2_1);
}

void NonMaxSuppression::thread_tmp_38_i_fu_414_p2() {
    tmp_38_i_fu_414_p2 = (!value_nms_1_fu_136.read().is_01() || !window_buf_1_2_val_fu_344_p4.read().is_01())? sc_lv<1>(): (sc_biguint<8>(value_nms_1_fu_136.read()) < sc_biguint<8>(window_buf_1_2_val_fu_344_p4.read()));
}

void NonMaxSuppression::thread_tmp_39_i_fu_440_p2() {
    tmp_39_i_fu_440_p2 = (!value_nms_1_fu_136.read().is_01() || !window_buf_0_1_val_fu_124.read().is_01())? sc_lv<1>(): (sc_biguint<8>(value_nms_1_fu_136.read()) < sc_biguint<8>(window_buf_0_1_val_fu_124.read()));
}

void NonMaxSuppression::thread_tmp_40_i_fu_452_p2() {
    tmp_40_i_fu_452_p2 = (!grad_nms_fu_148.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(grad_nms_fu_148.read() == ap_const_lv2_2);
}

void NonMaxSuppression::thread_tmp_41_i_fu_446_p2() {
    tmp_41_i_fu_446_p2 = (!value_nms_1_fu_136.read().is_01() || !fifo3_value_dout.read().is_01())? sc_lv<1>(): (sc_biguint<8>(value_nms_1_fu_136.read()) < sc_biguint<8>(fifo3_value_dout.read()));
}

void NonMaxSuppression::thread_tmp_42_i_fu_458_p2() {
    tmp_42_i_fu_458_p2 = (!value_nms_1_fu_136.read().is_01() || !window_buf_0_2_val_fu_334_p4.read().is_01())? sc_lv<1>(): (sc_biguint<8>(value_nms_1_fu_136.read()) < sc_biguint<8>(window_buf_0_2_val_fu_334_p4.read()));
}

void NonMaxSuppression::thread_tmp_43_i_fu_464_p2() {
    tmp_43_i_fu_464_p2 = (!value_nms_1_fu_136.read().is_01() || !window_buf_2_1_val_1_fu_144.read().is_01())? sc_lv<1>(): (sc_biguint<8>(value_nms_1_fu_136.read()) < sc_biguint<8>(window_buf_2_1_val_1_fu_144.read()));
}

void NonMaxSuppression::thread_tmp_44_i_fu_484_p2() {
    tmp_44_i_fu_484_p2 = (!grad_nms_fu_148.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(grad_nms_fu_148.read() == ap_const_lv2_3);
}

void NonMaxSuppression::thread_tmp_45_i_fu_490_p2() {
    tmp_45_i_fu_490_p2 = (!value_nms_1_fu_136.read().is_01() || !window_buf_2_1_val_fu_140.read().is_01())? sc_lv<1>(): (sc_biguint<8>(value_nms_1_fu_136.read()) < sc_biguint<8>(window_buf_2_1_val_fu_140.read()));
}

void NonMaxSuppression::thread_tmp_48_i_fu_307_p2() {
    tmp_48_i_fu_307_p2 = (!xi_i_reg_222.read().is_01() || !ap_const_lv10_1FD.is_01())? sc_lv<1>(): (sc_biguint<10>(xi_i_reg_222.read()) < sc_biguint<10>(ap_const_lv10_1FD));
}

void NonMaxSuppression::thread_tmp_fu_629_p2() {
    tmp_fu_629_p2 = (icmp3_reg_724_pp0_iter1_reg.read() & tmp_48_i_reg_729_pp0_iter1_reg.read());
}

void NonMaxSuppression::thread_tmp_i_fu_233_p2() {
    tmp_i_fu_233_p2 = (!yi_i_reg_211.read().is_01() || !ap_const_lv10_200.is_01())? sc_lv<1>(): sc_lv<1>(yi_i_reg_211.read() == ap_const_lv10_200);
}

void NonMaxSuppression::thread_value_nms_7_i_fu_622_p3() {
    value_nms_7_i_fu_622_p3 = (!sel_tmp1_reg_775.read()[0].is_01())? sc_lv<8>(): ((sel_tmp1_reg_775.read()[0].to_bool())? p_window_buf_1_1_va_2_fu_598_p3.read(): sel_tmp8_fu_615_p3.read());
}

void NonMaxSuppression::thread_window_buf_0_2_val_fu_334_p4() {
    window_buf_0_2_val_fu_334_p4 = line_buf_value_q0.read().range(15, 8);
}

void NonMaxSuppression::thread_window_buf_1_2_val_fu_344_p4() {
    window_buf_1_2_val_fu_344_p4 = line_buf_value_q0.read().range(23, 16);
}

void NonMaxSuppression::thread_xi_fu_279_p2() {
    xi_fu_279_p2 = (!xi_i_reg_222.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(xi_i_reg_222.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void NonMaxSuppression::thread_yi_fu_239_p2() {
    yi_fu_239_p2 = (!yi_i_reg_211.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(yi_i_reg_211.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void NonMaxSuppression::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_i_fu_233_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

