// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _NonMaxSuppression_HH_
#define _NonMaxSuppression_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Sobel_512u_512u_sfYi.h"
#include "NonMaxSuppressionmb6.h"

namespace ap_rtl {

struct NonMaxSuppression : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<8> > fifo3_value_dout;
    sc_in< sc_logic > fifo3_value_empty_n;
    sc_out< sc_logic > fifo3_value_read;
    sc_in< sc_lv<2> > fifo3_grad_dout;
    sc_in< sc_logic > fifo3_grad_empty_n;
    sc_out< sc_logic > fifo3_grad_read;
    sc_out< sc_lv<8> > fifo4_din;
    sc_in< sc_logic > fifo4_full_n;
    sc_out< sc_logic > fifo4_write;


    // Module declarations
    NonMaxSuppression(sc_module_name name);
    SC_HAS_PROCESS(NonMaxSuppression);

    ~NonMaxSuppression();

    sc_trace_file* mVcdFile;

    Sobel_512u_512u_sfYi* line_buf_value_U;
    NonMaxSuppressionmb6* line_buf_grad_U;
    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > fifo3_value_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > tmp_31_i_reg_703;
    sc_signal< sc_logic > fifo3_grad_blk_n;
    sc_signal< sc_logic > fifo4_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<1> > tmp_31_i_reg_703_pp0_iter1_reg;
    sc_signal< sc_lv<10> > xi_i_reg_222;
    sc_signal< sc_lv<1> > tmp_i_fu_233_p2;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<10> > yi_fu_239_p2;
    sc_signal< sc_lv<10> > yi_reg_693;
    sc_signal< sc_lv<1> > tmp1_fu_267_p2;
    sc_signal< sc_lv<1> > tmp1_reg_698;
    sc_signal< sc_lv<1> > tmp_31_i_fu_273_p2;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter2;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<10> > xi_fu_279_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<9> > line_buf_value_addr_reg_712;
    sc_signal< sc_lv<9> > line_buf_grad_addr_reg_718;
    sc_signal< sc_lv<1> > icmp3_fu_301_p2;
    sc_signal< sc_lv<1> > icmp3_reg_724;
    sc_signal< sc_lv<1> > icmp3_reg_724_pp0_iter1_reg;
    sc_signal< sc_lv<1> > tmp_48_i_fu_307_p2;
    sc_signal< sc_lv<1> > tmp_48_i_reg_729;
    sc_signal< sc_lv<1> > tmp_48_i_reg_729_pp0_iter1_reg;
    sc_signal< sc_lv<8> > window_buf_1_1_val_reg_734;
    sc_signal< sc_lv<1> > tmp_35_i_fu_402_p2;
    sc_signal< sc_lv<1> > tmp_35_i_reg_740;
    sc_signal< sc_lv<1> > tmp_37_i_fu_434_p2;
    sc_signal< sc_lv<1> > tmp_37_i_reg_745;
    sc_signal< sc_lv<1> > tmp_39_i_fu_440_p2;
    sc_signal< sc_lv<1> > tmp_39_i_reg_750;
    sc_signal< sc_lv<1> > tmp_41_i_fu_446_p2;
    sc_signal< sc_lv<1> > tmp_41_i_reg_755;
    sc_signal< sc_lv<1> > tmp_42_i_fu_458_p2;
    sc_signal< sc_lv<1> > tmp_42_i_reg_760;
    sc_signal< sc_lv<1> > tmp_45_i_fu_490_p2;
    sc_signal< sc_lv<1> > tmp_45_i_reg_765;
    sc_signal< sc_lv<8> > sel_tmp5_fu_522_p3;
    sc_signal< sc_lv<8> > sel_tmp5_reg_770;
    sc_signal< sc_lv<1> > sel_tmp1_fu_542_p2;
    sc_signal< sc_lv<1> > sel_tmp1_reg_775;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter1_state4;
    sc_signal< sc_lv<9> > line_buf_value_address0;
    sc_signal< sc_logic > line_buf_value_ce0;
    sc_signal< sc_lv<24> > line_buf_value_q0;
    sc_signal< sc_logic > line_buf_value_ce1;
    sc_signal< sc_logic > line_buf_value_we1;
    sc_signal< sc_lv<24> > line_buf_value_d1;
    sc_signal< sc_lv<9> > line_buf_grad_address0;
    sc_signal< sc_logic > line_buf_grad_ce0;
    sc_signal< sc_lv<6> > line_buf_grad_q0;
    sc_signal< sc_logic > line_buf_grad_ce1;
    sc_signal< sc_logic > line_buf_grad_we1;
    sc_signal< sc_lv<6> > line_buf_grad_d1;
    sc_signal< sc_lv<10> > yi_i_reg_211;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > tmp_32_i_fu_285_p1;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<8> > window_buf_0_1_val_fu_124;
    sc_signal< sc_lv<8> > window_buf_0_1_val_1_fu_128;
    sc_signal< sc_lv<8> > window_buf_0_2_val_fu_334_p4;
    sc_signal< sc_lv<8> > value_nms_fu_132;
    sc_signal< sc_lv<8> > value_nms_1_fu_136;
    sc_signal< sc_lv<8> > window_buf_1_2_val_fu_344_p4;
    sc_signal< sc_lv<8> > window_buf_2_1_val_fu_140;
    sc_signal< sc_lv<8> > window_buf_2_1_val_1_fu_144;
    sc_signal< sc_lv<2> > grad_nms_fu_148;
    sc_signal< sc_lv<8> > tmp_12_fu_245_p4;
    sc_signal< sc_lv<1> > icmp_fu_255_p2;
    sc_signal< sc_lv<1> > tmp_30_i_fu_261_p2;
    sc_signal< sc_lv<8> > tmp_13_fu_291_p4;
    sc_signal< sc_lv<16> > tmp_21_i_fu_364_p4;
    sc_signal< sc_lv<4> > tmp_23_i_fu_383_p4;
    sc_signal< sc_lv<1> > tmp_36_i_fu_408_p2;
    sc_signal< sc_lv<1> > tmp_38_i_fu_414_p2;
    sc_signal< sc_lv<1> > or_cond_fu_420_p2;
    sc_signal< sc_lv<1> > tmp_43_i_fu_464_p2;
    sc_signal< sc_lv<1> > or_cond1_i_fu_470_p2;
    sc_signal< sc_lv<1> > sel_tmp2_demorgan_fu_496_p2;
    sc_signal< sc_lv<1> > tmp_40_i_fu_452_p2;
    sc_signal< sc_lv<1> > sel_tmp2_fu_502_p2;
    sc_signal< sc_lv<1> > sel_tmp3_fu_508_p2;
    sc_signal< sc_lv<8> > p_window_buf_value_lo_fu_476_p3;
    sc_signal< sc_lv<8> > p_window_buf_1_1_va_fu_426_p3;
    sc_signal< sc_lv<8> > sel_tmp4_fu_514_p3;
    sc_signal< sc_lv<1> > sel_tmp13_demorgan_fu_530_p2;
    sc_signal< sc_lv<1> > tmp_44_i_fu_484_p2;
    sc_signal< sc_lv<1> > sel_tmp_fu_536_p2;
    sc_signal< sc_lv<1> > or_cond1_fu_583_p2;
    sc_signal< sc_lv<1> > or_cond2_fu_594_p2;
    sc_signal< sc_lv<1> > sel_tmp6_fu_605_p2;
    sc_signal< sc_lv<1> > sel_tmp7_fu_610_p2;
    sc_signal< sc_lv<8> > p_window_buf_1_1_va_1_fu_587_p3;
    sc_signal< sc_lv<8> > p_window_buf_1_1_va_2_fu_598_p3;
    sc_signal< sc_lv<8> > sel_tmp8_fu_615_p3;
    sc_signal< sc_lv<1> > tmp_fu_629_p2;
    sc_signal< sc_lv<1> > or_cond5_i_fu_633_p2;
    sc_signal< sc_lv<8> > value_nms_7_i_fu_622_p3;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_pp0_stage0;
    static const sc_lv<4> ap_ST_fsm_state6;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<10> ap_const_lv10_200;
    static const sc_lv<10> ap_const_lv10_1;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<10> ap_const_lv10_1FD;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state6();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state3_pp0_stage0_iter0();
    void thread_ap_block_state4_pp0_stage0_iter1();
    void thread_ap_block_state5_pp0_stage0_iter2();
    void thread_ap_condition_pp0_exit_iter1_state4();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_fifo3_grad_blk_n();
    void thread_fifo3_grad_read();
    void thread_fifo3_value_blk_n();
    void thread_fifo3_value_read();
    void thread_fifo4_blk_n();
    void thread_fifo4_din();
    void thread_fifo4_write();
    void thread_icmp3_fu_301_p2();
    void thread_icmp_fu_255_p2();
    void thread_internal_ap_ready();
    void thread_line_buf_grad_address0();
    void thread_line_buf_grad_ce0();
    void thread_line_buf_grad_ce1();
    void thread_line_buf_grad_d1();
    void thread_line_buf_grad_we1();
    void thread_line_buf_value_address0();
    void thread_line_buf_value_ce0();
    void thread_line_buf_value_ce1();
    void thread_line_buf_value_d1();
    void thread_line_buf_value_we1();
    void thread_or_cond1_fu_583_p2();
    void thread_or_cond1_i_fu_470_p2();
    void thread_or_cond2_fu_594_p2();
    void thread_or_cond5_i_fu_633_p2();
    void thread_or_cond_fu_420_p2();
    void thread_p_window_buf_1_1_va_1_fu_587_p3();
    void thread_p_window_buf_1_1_va_2_fu_598_p3();
    void thread_p_window_buf_1_1_va_fu_426_p3();
    void thread_p_window_buf_value_lo_fu_476_p3();
    void thread_real_start();
    void thread_sel_tmp13_demorgan_fu_530_p2();
    void thread_sel_tmp1_fu_542_p2();
    void thread_sel_tmp2_demorgan_fu_496_p2();
    void thread_sel_tmp2_fu_502_p2();
    void thread_sel_tmp3_fu_508_p2();
    void thread_sel_tmp4_fu_514_p3();
    void thread_sel_tmp5_fu_522_p3();
    void thread_sel_tmp6_fu_605_p2();
    void thread_sel_tmp7_fu_610_p2();
    void thread_sel_tmp8_fu_615_p3();
    void thread_sel_tmp_fu_536_p2();
    void thread_start_out();
    void thread_start_write();
    void thread_tmp1_fu_267_p2();
    void thread_tmp_12_fu_245_p4();
    void thread_tmp_13_fu_291_p4();
    void thread_tmp_21_i_fu_364_p4();
    void thread_tmp_23_i_fu_383_p4();
    void thread_tmp_30_i_fu_261_p2();
    void thread_tmp_31_i_fu_273_p2();
    void thread_tmp_32_i_fu_285_p1();
    void thread_tmp_35_i_fu_402_p2();
    void thread_tmp_36_i_fu_408_p2();
    void thread_tmp_37_i_fu_434_p2();
    void thread_tmp_38_i_fu_414_p2();
    void thread_tmp_39_i_fu_440_p2();
    void thread_tmp_40_i_fu_452_p2();
    void thread_tmp_41_i_fu_446_p2();
    void thread_tmp_42_i_fu_458_p2();
    void thread_tmp_43_i_fu_464_p2();
    void thread_tmp_44_i_fu_484_p2();
    void thread_tmp_45_i_fu_490_p2();
    void thread_tmp_48_i_fu_307_p2();
    void thread_tmp_fu_629_p2();
    void thread_tmp_i_fu_233_p2();
    void thread_value_nms_7_i_fu_622_p3();
    void thread_window_buf_0_2_val_fu_334_p4();
    void thread_window_buf_1_2_val_fu_344_p4();
    void thread_xi_fu_279_p2();
    void thread_yi_fu_239_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
